// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        ap_return_0,
        ap_return_1,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] p_read;
input  [7:0] p_read1;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
input   ap_ce;

reg[7:0] ap_return_0;
reg[7:0] ap_return_1;

reg  signed [7:0] p_read_12_reg_148;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg  signed [7:0] p_read_12_reg_148_pp0_iter1_reg;
reg  signed [7:0] p_read_12_reg_148_pp0_iter2_reg;
reg   [7:0] trunc_ln_reg_163;
reg   [7:0] trunc_ln818_s_reg_168;
wire   [5:0] grp_fu_46_p1;
wire    ap_block_pp0_stage0;
wire  signed [5:0] grp_fu_49_p1;
wire   [10:0] grp_fu_46_p2;
wire   [10:0] grp_fu_49_p2;
wire   [7:0] shl_ln818_fu_127_p2;
wire   [7:0] add_ln813_fu_132_p2;
reg    grp_fu_46_ce;
reg    grp_fu_49_ce;
reg    ap_ce_reg;
reg  signed [7:0] p_read_int_reg;
reg  signed [7:0] p_read1_int_reg;
reg   [7:0] ap_return_0_int_reg;
reg   [7:0] ap_return_1_int_reg;

myproject_mul_8s_6ns_11_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_8s_6ns_11_3_0_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_read_int_reg),
    .din1(grp_fu_46_p1),
    .ce(grp_fu_46_ce),
    .dout(grp_fu_46_p2)
);

myproject_mul_8s_6s_11_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_8s_6s_11_3_0_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_read1_int_reg),
    .din1(grp_fu_49_p1),
    .ce(grp_fu_49_ce),
    .dout(grp_fu_49_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg[7 : 1] <= shl_ln818_fu_127_p2[7 : 1];
        ap_return_1_int_reg <= add_ln813_fu_132_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read1_int_reg <= p_read1;
        p_read_int_reg <= p_read;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        p_read_12_reg_148 <= p_read_int_reg;
        p_read_12_reg_148_pp0_iter1_reg <= p_read_12_reg_148;
        p_read_12_reg_148_pp0_iter2_reg <= p_read_12_reg_148_pp0_iter1_reg;
        trunc_ln818_s_reg_168 <= {{grp_fu_49_p2[10:3]}};
        trunc_ln_reg_163 <= {{grp_fu_46_p2[10:3]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = shl_ln818_fu_127_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln813_fu_132_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_46_ce = 1'b1;
    end else begin
        grp_fu_46_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_49_ce = 1'b1;
    end else begin
        grp_fu_49_ce = 1'b0;
    end
end

assign add_ln813_fu_132_p2 = (trunc_ln818_s_reg_168 + trunc_ln_reg_163);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign grp_fu_46_p1 = 11'd22;

assign grp_fu_49_p1 = 11'd2022;

assign shl_ln818_fu_127_p2 = p_read_12_reg_148_pp0_iter2_reg << 8'd1;

always @ (posedge ap_clk) begin
    ap_return_0_int_reg[0] <= 1'b0;
end

endmodule //myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config11_s
