// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_relu_config4_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);


output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;

wire   [0:0] icmp_ln1649_fu_88_p2;
wire   [6:0] trunc_ln40_8_fu_84_p1;
wire   [6:0] datareg_V_fu_94_p3;
wire   [0:0] icmp_ln1649_4_fu_106_p2;
wire   [6:0] trunc_ln40_7_fu_80_p1;
wire   [6:0] datareg_V_4_fu_112_p3;
wire   [0:0] icmp_ln1649_5_fu_124_p2;
wire   [6:0] trunc_ln40_6_fu_76_p1;
wire   [6:0] datareg_V_5_fu_130_p3;
wire   [0:0] icmp_ln1649_6_fu_142_p2;
wire   [6:0] trunc_ln40_5_fu_72_p1;
wire   [6:0] datareg_V_6_fu_148_p3;
wire   [0:0] icmp_ln1649_7_fu_160_p2;
wire   [6:0] trunc_ln40_4_fu_68_p1;
wire   [6:0] datareg_V_7_fu_166_p3;
wire   [0:0] icmp_ln1649_8_fu_178_p2;
wire   [6:0] trunc_ln40_fu_64_p1;
wire   [6:0] datareg_V_8_fu_184_p3;
wire   [7:0] zext_ln45_fu_102_p1;
wire   [7:0] zext_ln45_4_fu_120_p1;
wire   [7:0] zext_ln45_5_fu_138_p1;
wire   [7:0] zext_ln45_6_fu_156_p1;
wire   [7:0] zext_ln45_7_fu_174_p1;
wire   [7:0] zext_ln45_8_fu_192_p1;

assign ap_ready = 1'b1;

assign datareg_V_4_fu_112_p3 = ((icmp_ln1649_4_fu_106_p2[0:0] == 1'b1) ? trunc_ln40_7_fu_80_p1 : 7'd0);

assign datareg_V_5_fu_130_p3 = ((icmp_ln1649_5_fu_124_p2[0:0] == 1'b1) ? trunc_ln40_6_fu_76_p1 : 7'd0);

assign datareg_V_6_fu_148_p3 = ((icmp_ln1649_6_fu_142_p2[0:0] == 1'b1) ? trunc_ln40_5_fu_72_p1 : 7'd0);

assign datareg_V_7_fu_166_p3 = ((icmp_ln1649_7_fu_160_p2[0:0] == 1'b1) ? trunc_ln40_4_fu_68_p1 : 7'd0);

assign datareg_V_8_fu_184_p3 = ((icmp_ln1649_8_fu_178_p2[0:0] == 1'b1) ? trunc_ln40_fu_64_p1 : 7'd0);

assign datareg_V_fu_94_p3 = ((icmp_ln1649_fu_88_p2[0:0] == 1'b1) ? trunc_ln40_8_fu_84_p1 : 7'd0);

assign trunc_ln40_4_fu_68_p1 = p_read4[6:0];

assign trunc_ln40_5_fu_72_p1 = p_read3[6:0];

assign trunc_ln40_6_fu_76_p1 = p_read2[6:0];

assign trunc_ln40_7_fu_80_p1 = p_read1[6:0];

assign trunc_ln40_8_fu_84_p1 = p_read[6:0];

assign trunc_ln40_fu_64_p1 = p_read5[6:0];

assign zext_ln45_4_fu_120_p1 = datareg_V_4_fu_112_p3;

assign zext_ln45_5_fu_138_p1 = datareg_V_5_fu_130_p3;

assign zext_ln45_6_fu_156_p1 = datareg_V_6_fu_148_p3;

assign zext_ln45_7_fu_174_p1 = datareg_V_7_fu_166_p3;

assign zext_ln45_8_fu_192_p1 = datareg_V_8_fu_184_p3;

assign zext_ln45_fu_102_p1 = datareg_V_fu_94_p3;

assign ap_return_0 = zext_ln45_fu_102_p1;

assign ap_return_1 = zext_ln45_4_fu_120_p1;

assign ap_return_2 = zext_ln45_5_fu_138_p1;

assign ap_return_3 = zext_ln45_6_fu_156_p1;

assign ap_return_4 = zext_ln45_7_fu_174_p1;

assign ap_return_5 = zext_ln45_8_fu_192_p1;

assign icmp_ln1649_4_fu_106_p2 = (($signed(p_read1) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_5_fu_124_p2 = (($signed(p_read2) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_6_fu_142_p2 = (($signed(p_read3) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_7_fu_160_p2 = (($signed(p_read4) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_8_fu_178_p2 = (($signed(p_read5) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_fu_88_p2 = (($signed(p_read) > $signed(8'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_relu_config4_s
