// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
input   ap_ce;

reg[7:0] ap_return_0;
reg[7:0] ap_return_1;
reg[7:0] ap_return_2;
reg[7:0] ap_return_3;

reg  signed [7:0] p_read_9_reg_769;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg  signed [7:0] p_read28_reg_775;
reg  signed [7:0] p_read17_reg_781;
reg  signed [7:0] p_read_10_reg_788;
reg   [5:0] trunc_ln818_s_reg_794;
reg   [6:0] trunc_ln818_3_reg_799;
reg   [5:0] trunc_ln818_5_reg_804;
reg   [7:0] trunc_ln818_6_reg_809;
reg   [6:0] trunc_ln818_11_reg_814;
reg   [7:0] trunc_ln818_17_reg_819;
reg   [7:0] trunc_ln818_19_reg_824;
wire   [6:0] add_ln813_6_fu_486_p2;
reg   [6:0] add_ln813_6_reg_829;
wire   [7:0] add_ln813_11_fu_492_p2;
reg   [7:0] add_ln813_11_reg_834;
wire   [7:0] add_ln813_14_fu_498_p2;
reg   [7:0] add_ln813_14_reg_839;
wire   [7:0] add_ln813_16_fu_504_p2;
reg   [7:0] add_ln813_16_reg_844;
wire   [7:0] add_ln813_20_fu_510_p2;
reg   [7:0] add_ln813_20_reg_849;
reg   [7:0] trunc_ln818_2_reg_854;
wire  signed [7:0] sext_ln818_7_fu_579_p1;
reg  signed [7:0] sext_ln818_7_reg_859;
wire   [7:0] add_ln813_fu_679_p2;
reg   [7:0] add_ln813_reg_864;
wire   [7:0] add_ln813_7_fu_688_p2;
reg   [7:0] add_ln813_7_reg_869;
reg   [7:0] add_ln813_7_reg_869_pp0_iter2_reg;
wire   [7:0] add_ln813_9_fu_693_p2;
reg   [7:0] add_ln813_9_reg_874;
wire   [7:0] add_ln813_12_fu_698_p2;
reg   [7:0] add_ln813_12_reg_879;
reg   [7:0] add_ln813_12_reg_879_pp0_iter2_reg;
wire   [7:0] add_ln813_15_fu_703_p2;
reg   [7:0] add_ln813_15_reg_884;
wire   [7:0] add_ln813_17_fu_708_p2;
reg   [7:0] add_ln813_17_reg_889;
wire   [7:0] add_ln813_19_fu_712_p2;
reg   [7:0] add_ln813_19_reg_894;
wire   [7:0] add_ln813_21_fu_718_p2;
reg   [7:0] add_ln813_21_reg_899;
wire   [7:0] add_ln813_5_fu_723_p2;
reg   [7:0] add_ln813_5_reg_904;
wire   [7:0] add_ln813_10_fu_727_p2;
reg   [7:0] add_ln813_10_reg_909;
wire   [7:0] add_ln813_18_fu_731_p2;
reg   [7:0] add_ln813_18_reg_914;
wire   [7:0] add_ln813_22_fu_735_p2;
reg   [7:0] add_ln813_22_reg_919;
wire  signed [7:0] sext_ln818_fu_108_p0;
wire    ap_block_pp0_stage0;
wire  signed [7:0] sext_ln818_3_fu_112_p0;
wire  signed [7:0] trunc_ln818_8_fu_116_p1;
wire   [5:0] trunc_ln818_8_fu_116_p4;
wire  signed [8:0] sext_ln818_3_fu_112_p1;
wire   [8:0] r_V_fu_130_p2;
wire  signed [7:0] tmp_fu_146_p1;
wire   [9:0] tmp_fu_146_p3;
wire  signed [10:0] sext_ln818_fu_108_p1;
wire  signed [10:0] sext_ln1273_21_fu_154_p1;
wire   [10:0] r_V_5_fu_158_p2;
wire  signed [7:0] shl_ln1273_7_fu_174_p1;
wire   [8:0] shl_ln1273_7_fu_174_p3;
wire  signed [9:0] sext_ln1273_7_fu_182_p1;
wire   [9:0] r_V_7_fu_186_p2;
wire  signed [7:0] sext_ln1273_9_fu_202_p0;
wire  signed [7:0] sext_ln1273_10_fu_206_p0;
wire  signed [8:0] sext_ln1273_10_fu_206_p1;
wire   [8:0] r_V_9_fu_210_p2;
wire  signed [7:0] shl_ln1273_9_fu_226_p1;
wire   [9:0] shl_ln1273_9_fu_226_p3;
wire  signed [10:0] sext_ln1273_11_fu_234_p1;
wire   [10:0] r_V_11_fu_238_p2;
wire  signed [10:0] sext_ln1273_9_fu_202_p1;
wire   [10:0] r_V_10_fu_244_p2;
wire  signed [7:0] shl_ln1273_2_fu_270_p1;
wire   [8:0] shl_ln1273_2_fu_270_p3;
wire  signed [9:0] sext_ln1273_14_fu_278_p1;
wire   [9:0] r_V_13_fu_282_p2;
wire  signed [7:0] trunc_ln_fu_298_p1;
wire   [6:0] trunc_ln_fu_298_p4;
wire  signed [7:0] sext_ln70_fu_312_p0;
wire  signed [7:0] trunc_ln818_13_fu_316_p1;
wire   [4:0] trunc_ln818_13_fu_316_p4;
wire  signed [7:0] shl_ln1273_4_fu_330_p1;
wire  signed [7:0] shl_ln1273_5_fu_338_p1;
wire   [8:0] shl_ln1273_5_fu_338_p3;
wire   [10:0] shl_ln1273_4_fu_330_p3;
wire  signed [10:0] sext_ln1273_17_fu_346_p1;
wire   [10:0] r_V_15_fu_350_p2;
wire  signed [7:0] trunc_ln818_15_fu_366_p1;
wire   [6:0] trunc_ln818_15_fu_366_p4;
wire  signed [7:0] shl_ln1273_10_fu_380_p1;
wire   [9:0] shl_ln1273_10_fu_380_p3;
wire  signed [10:0] sext_ln1273_18_fu_388_p1;
wire  signed [10:0] sext_ln70_fu_312_p1;
wire   [10:0] r_V_16_fu_392_p2;
wire  signed [7:0] sext_ln1273_19_fu_408_p0;
wire  signed [7:0] shl_ln1273_11_fu_412_p1;
wire   [9:0] shl_ln1273_11_fu_412_p3;
wire  signed [10:0] sext_ln1273_20_fu_420_p1;
wire  signed [10:0] sext_ln1273_19_fu_408_p1;
wire   [10:0] r_V_17_fu_424_p2;
wire   [10:0] r_V_18_fu_440_p2;
wire   [10:0] r_V_19_fu_456_p2;
wire  signed [7:0] trunc_ln818_20_fu_472_p1;
wire   [6:0] trunc_ln818_20_fu_472_p4;
wire  signed [6:0] sext_ln1273_fu_126_p1;
wire  signed [6:0] sext_ln1273_16_fu_326_p1;
wire   [7:0] trunc_ln818_14_fu_356_p4;
wire   [7:0] trunc_ln818_18_fu_446_p4;
wire   [7:0] trunc_ln818_9_fu_164_p4;
wire   [7:0] trunc_ln818_7_fu_260_p4;
wire  signed [7:0] sext_ln818_2_fu_308_p1;
wire  signed [7:0] sext_ln818_4_fu_376_p1;
wire   [7:0] trunc_ln818_16_fu_398_p4;
wire  signed [7:0] sext_ln818_5_fu_482_p1;
wire   [8:0] shl_ln1273_6_fu_526_p3;
wire  signed [10:0] sext_ln1273_5_fu_533_p1;
wire   [10:0] shl_ln_fu_519_p3;
wire   [10:0] r_V_6_fu_537_p2;
wire  signed [10:0] sext_ln1273_6_fu_553_p1;
wire   [10:0] p_shl_fu_556_p3;
wire   [10:0] sub_ln1270_fu_563_p2;
wire   [9:0] shl_ln1273_8_fu_582_p3;
wire  signed [10:0] sext_ln1273_8_fu_589_p1;
wire   [10:0] r_V_8_fu_593_p2;
wire   [8:0] shl_ln1273_1_fu_619_p3;
wire  signed [10:0] sext_ln1273_12_fu_626_p1;
wire   [10:0] shl_ln1273_s_fu_612_p3;
wire   [10:0] r_V_12_fu_630_p2;
wire   [9:0] shl_ln1273_3_fu_652_p3;
wire  signed [10:0] sext_ln1273_15_fu_659_p1;
wire  signed [10:0] sext_ln1273_13_fu_646_p1;
wire   [10:0] r_V_14_fu_663_p2;
wire  signed [7:0] sext_ln818_8_fu_609_p1;
wire  signed [7:0] sext_ln818_9_fu_649_p1;
wire  signed [7:0] sext_ln813_fu_685_p1;
wire  signed [7:0] sext_ln818_6_fu_516_p1;
wire   [7:0] trunc_ln818_12_fu_669_p4;
wire   [7:0] trunc_ln818_4_fu_599_p4;
wire   [7:0] trunc_ln818_1_fu_543_p4;
wire   [7:0] trunc_ln818_10_fu_636_p4;
wire   [7:0] add_ln813_8_fu_739_p2;
wire   [7:0] add_ln813_13_fu_743_p2;
reg    ap_ce_reg;
reg   [7:0] p_read_int_reg;
reg   [7:0] p_read1_int_reg;
reg   [7:0] p_read2_int_reg;
reg   [7:0] p_read3_int_reg;
reg   [7:0] p_read4_int_reg;
reg   [7:0] p_read5_int_reg;
reg   [7:0] ap_return_0_int_reg;
reg   [7:0] ap_return_1_int_reg;
reg   [7:0] ap_return_2_int_reg;
reg   [7:0] ap_return_3_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln813_10_reg_909 <= add_ln813_10_fu_727_p2;
        add_ln813_11_reg_834 <= add_ln813_11_fu_492_p2;
        add_ln813_12_reg_879 <= add_ln813_12_fu_698_p2;
        add_ln813_12_reg_879_pp0_iter2_reg <= add_ln813_12_reg_879;
        add_ln813_14_reg_839 <= add_ln813_14_fu_498_p2;
        add_ln813_15_reg_884 <= add_ln813_15_fu_703_p2;
        add_ln813_16_reg_844 <= add_ln813_16_fu_504_p2;
        add_ln813_17_reg_889 <= add_ln813_17_fu_708_p2;
        add_ln813_18_reg_914 <= add_ln813_18_fu_731_p2;
        add_ln813_19_reg_894 <= add_ln813_19_fu_712_p2;
        add_ln813_20_reg_849 <= add_ln813_20_fu_510_p2;
        add_ln813_21_reg_899 <= add_ln813_21_fu_718_p2;
        add_ln813_22_reg_919 <= add_ln813_22_fu_735_p2;
        add_ln813_5_reg_904 <= add_ln813_5_fu_723_p2;
        add_ln813_6_reg_829 <= add_ln813_6_fu_486_p2;
        add_ln813_7_reg_869 <= add_ln813_7_fu_688_p2;
        add_ln813_7_reg_869_pp0_iter2_reg <= add_ln813_7_reg_869;
        add_ln813_9_reg_874 <= add_ln813_9_fu_693_p2;
        add_ln813_reg_864 <= add_ln813_fu_679_p2;
        p_read17_reg_781 <= p_read1_int_reg;
        p_read28_reg_775 <= p_read2_int_reg;
        p_read_10_reg_788 <= p_read_int_reg;
        p_read_9_reg_769 <= p_read3_int_reg;
        sext_ln818_7_reg_859 <= sext_ln818_7_fu_579_p1;
        trunc_ln818_11_reg_814 <= {{r_V_13_fu_282_p2[9:3]}};
        trunc_ln818_17_reg_819 <= {{r_V_17_fu_424_p2[10:3]}};
        trunc_ln818_19_reg_824 <= {{r_V_19_fu_456_p2[10:3]}};
        trunc_ln818_2_reg_854 <= {{sub_ln1270_fu_563_p2[10:3]}};
        trunc_ln818_3_reg_799 <= {{r_V_7_fu_186_p2[9:3]}};
        trunc_ln818_5_reg_804 <= {{r_V_9_fu_210_p2[8:3]}};
        trunc_ln818_6_reg_809 <= {{r_V_10_fu_244_p2[10:3]}};
        trunc_ln818_s_reg_794 <= {{r_V_fu_130_p2[8:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln813_8_fu_739_p2;
        ap_return_1_int_reg <= add_ln813_13_fu_743_p2;
        ap_return_2_int_reg <= add_ln813_18_reg_914;
        ap_return_3_int_reg <= add_ln813_22_reg_919;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read_int_reg <= p_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln813_8_fu_739_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln813_13_fu_743_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln813_18_reg_914;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln813_22_reg_919;
    end else begin
        ap_return_3 = 'bx;
    end
end

assign add_ln813_10_fu_727_p2 = ($signed(add_ln813_9_reg_874) + $signed(sext_ln818_7_reg_859));

assign add_ln813_11_fu_492_p2 = (trunc_ln818_14_fu_356_p4 + trunc_ln818_18_fu_446_p4);

assign add_ln813_12_fu_698_p2 = (add_ln813_11_reg_834 + trunc_ln818_12_fu_669_p4);

assign add_ln813_13_fu_743_p2 = (add_ln813_12_reg_879_pp0_iter2_reg + add_ln813_10_reg_909);

assign add_ln813_14_fu_498_p2 = (trunc_ln818_9_fu_164_p4 + trunc_ln818_7_fu_260_p4);

assign add_ln813_15_fu_703_p2 = (add_ln813_14_reg_839 + trunc_ln818_4_fu_599_p4);

assign add_ln813_16_fu_504_p2 = ($signed(sext_ln818_2_fu_308_p1) + $signed(sext_ln818_4_fu_376_p1));

assign add_ln813_17_fu_708_p2 = (add_ln813_16_reg_844 + trunc_ln818_19_reg_824);

assign add_ln813_18_fu_731_p2 = (add_ln813_17_reg_889 + add_ln813_15_reg_884);

assign add_ln813_19_fu_712_p2 = ($signed(sext_ln818_7_fu_579_p1) + $signed(trunc_ln818_1_fu_543_p4));

assign add_ln813_20_fu_510_p2 = ($signed(trunc_ln818_16_fu_398_p4) + $signed(sext_ln818_5_fu_482_p1));

assign add_ln813_21_fu_718_p2 = (add_ln813_20_reg_849 + trunc_ln818_10_fu_636_p4);

assign add_ln813_22_fu_735_p2 = (add_ln813_21_reg_899 + add_ln813_19_reg_894);

assign add_ln813_5_fu_723_p2 = (add_ln813_reg_864 + trunc_ln818_2_reg_854);

assign add_ln813_6_fu_486_p2 = ($signed(sext_ln1273_fu_126_p1) + $signed(sext_ln1273_16_fu_326_p1));

assign add_ln813_7_fu_688_p2 = ($signed(sext_ln813_fu_685_p1) + $signed(trunc_ln818_17_reg_819));

assign add_ln813_8_fu_739_p2 = (add_ln813_7_reg_869_pp0_iter2_reg + add_ln813_5_reg_904);

assign add_ln813_9_fu_693_p2 = ($signed(sext_ln818_6_fu_516_p1) + $signed(trunc_ln818_6_reg_809));

assign add_ln813_fu_679_p2 = ($signed(sext_ln818_8_fu_609_p1) + $signed(sext_ln818_9_fu_649_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign p_shl_fu_556_p3 = {{p_read17_reg_781}, {3'd0}};

assign r_V_10_fu_244_p2 = ($signed(r_V_11_fu_238_p2) - $signed(sext_ln1273_9_fu_202_p1));

assign r_V_11_fu_238_p2 = ($signed(11'd0) - $signed(sext_ln1273_11_fu_234_p1));

assign r_V_12_fu_630_p2 = ($signed(sext_ln1273_12_fu_626_p1) - $signed(shl_ln1273_s_fu_612_p3));

assign r_V_13_fu_282_p2 = ($signed(10'd0) - $signed(sext_ln1273_14_fu_278_p1));

assign r_V_14_fu_663_p2 = ($signed(sext_ln1273_15_fu_659_p1) - $signed(sext_ln1273_13_fu_646_p1));

assign r_V_15_fu_350_p2 = ($signed(shl_ln1273_4_fu_330_p3) - $signed(sext_ln1273_17_fu_346_p1));

assign r_V_16_fu_392_p2 = ($signed(sext_ln1273_18_fu_388_p1) - $signed(sext_ln70_fu_312_p1));

assign r_V_17_fu_424_p2 = ($signed(sext_ln1273_20_fu_420_p1) + $signed(sext_ln1273_19_fu_408_p1));

assign r_V_18_fu_440_p2 = ($signed(11'd0) - $signed(sext_ln1273_20_fu_420_p1));

assign r_V_19_fu_456_p2 = ($signed(r_V_18_fu_440_p2) - $signed(sext_ln1273_19_fu_408_p1));

assign r_V_5_fu_158_p2 = ($signed(sext_ln818_fu_108_p1) - $signed(sext_ln1273_21_fu_154_p1));

assign r_V_6_fu_537_p2 = ($signed(sext_ln1273_5_fu_533_p1) - $signed(shl_ln_fu_519_p3));

assign r_V_7_fu_186_p2 = ($signed(10'd0) - $signed(sext_ln1273_7_fu_182_p1));

assign r_V_8_fu_593_p2 = ($signed(sext_ln1273_8_fu_589_p1) - $signed(sext_ln1273_6_fu_553_p1));

assign r_V_9_fu_210_p2 = ($signed(9'd0) - $signed(sext_ln1273_10_fu_206_p1));

assign r_V_fu_130_p2 = ($signed(9'd0) - $signed(sext_ln818_3_fu_112_p1));

assign sext_ln1273_10_fu_206_p0 = p_read2_int_reg;

assign sext_ln1273_10_fu_206_p1 = sext_ln1273_10_fu_206_p0;

assign sext_ln1273_11_fu_234_p1 = $signed(shl_ln1273_9_fu_226_p3);

assign sext_ln1273_12_fu_626_p1 = $signed(shl_ln1273_1_fu_619_p3);

assign sext_ln1273_13_fu_646_p1 = p_read_9_reg_769;

assign sext_ln1273_14_fu_278_p1 = $signed(shl_ln1273_2_fu_270_p3);

assign sext_ln1273_15_fu_659_p1 = $signed(shl_ln1273_3_fu_652_p3);

assign sext_ln1273_16_fu_326_p1 = $signed(trunc_ln818_13_fu_316_p4);

assign sext_ln1273_17_fu_346_p1 = $signed(shl_ln1273_5_fu_338_p3);

assign sext_ln1273_18_fu_388_p1 = $signed(shl_ln1273_10_fu_380_p3);

assign sext_ln1273_19_fu_408_p0 = p_read5_int_reg;

assign sext_ln1273_19_fu_408_p1 = sext_ln1273_19_fu_408_p0;

assign sext_ln1273_20_fu_420_p1 = $signed(shl_ln1273_11_fu_412_p3);

assign sext_ln1273_21_fu_154_p1 = $signed(tmp_fu_146_p3);

assign sext_ln1273_5_fu_533_p1 = $signed(shl_ln1273_6_fu_526_p3);

assign sext_ln1273_6_fu_553_p1 = p_read17_reg_781;

assign sext_ln1273_7_fu_182_p1 = $signed(shl_ln1273_7_fu_174_p3);

assign sext_ln1273_8_fu_589_p1 = $signed(shl_ln1273_8_fu_582_p3);

assign sext_ln1273_9_fu_202_p0 = p_read2_int_reg;

assign sext_ln1273_9_fu_202_p1 = sext_ln1273_9_fu_202_p0;

assign sext_ln1273_fu_126_p1 = $signed(trunc_ln818_8_fu_116_p4);

assign sext_ln70_fu_312_p0 = p_read4_int_reg;

assign sext_ln70_fu_312_p1 = sext_ln70_fu_312_p0;

assign sext_ln813_fu_685_p1 = $signed(add_ln813_6_reg_829);

assign sext_ln818_2_fu_308_p1 = $signed(trunc_ln_fu_298_p4);

assign sext_ln818_3_fu_112_p0 = p_read_int_reg;

assign sext_ln818_3_fu_112_p1 = sext_ln818_3_fu_112_p0;

assign sext_ln818_4_fu_376_p1 = $signed(trunc_ln818_15_fu_366_p4);

assign sext_ln818_5_fu_482_p1 = $signed(trunc_ln818_20_fu_472_p4);

assign sext_ln818_6_fu_516_p1 = $signed(trunc_ln818_s_reg_794);

assign sext_ln818_7_fu_579_p1 = $signed(trunc_ln818_3_reg_799);

assign sext_ln818_8_fu_609_p1 = $signed(trunc_ln818_5_reg_804);

assign sext_ln818_9_fu_649_p1 = $signed(trunc_ln818_11_reg_814);

assign sext_ln818_fu_108_p0 = p_read_int_reg;

assign sext_ln818_fu_108_p1 = sext_ln818_fu_108_p0;

assign shl_ln1273_10_fu_380_p1 = p_read4_int_reg;

assign shl_ln1273_10_fu_380_p3 = {{shl_ln1273_10_fu_380_p1}, {2'd0}};

assign shl_ln1273_11_fu_412_p1 = p_read5_int_reg;

assign shl_ln1273_11_fu_412_p3 = {{shl_ln1273_11_fu_412_p1}, {2'd0}};

assign shl_ln1273_1_fu_619_p3 = {{p_read28_reg_775}, {1'd0}};

assign shl_ln1273_2_fu_270_p1 = p_read3_int_reg;

assign shl_ln1273_2_fu_270_p3 = {{shl_ln1273_2_fu_270_p1}, {1'd0}};

assign shl_ln1273_3_fu_652_p3 = {{p_read_9_reg_769}, {2'd0}};

assign shl_ln1273_4_fu_330_p1 = p_read4_int_reg;

assign shl_ln1273_4_fu_330_p3 = {{shl_ln1273_4_fu_330_p1}, {3'd0}};

assign shl_ln1273_5_fu_338_p1 = p_read4_int_reg;

assign shl_ln1273_5_fu_338_p3 = {{shl_ln1273_5_fu_338_p1}, {1'd0}};

assign shl_ln1273_6_fu_526_p3 = {{p_read_10_reg_788}, {1'd0}};

assign shl_ln1273_7_fu_174_p1 = p_read1_int_reg;

assign shl_ln1273_7_fu_174_p3 = {{shl_ln1273_7_fu_174_p1}, {1'd0}};

assign shl_ln1273_8_fu_582_p3 = {{p_read17_reg_781}, {2'd0}};

assign shl_ln1273_9_fu_226_p1 = p_read2_int_reg;

assign shl_ln1273_9_fu_226_p3 = {{shl_ln1273_9_fu_226_p1}, {2'd0}};

assign shl_ln1273_s_fu_612_p3 = {{p_read28_reg_775}, {3'd0}};

assign shl_ln_fu_519_p3 = {{p_read_10_reg_788}, {3'd0}};

assign sub_ln1270_fu_563_p2 = ($signed(sext_ln1273_6_fu_553_p1) - $signed(p_shl_fu_556_p3));

assign tmp_fu_146_p1 = p_read_int_reg;

assign tmp_fu_146_p3 = {{tmp_fu_146_p1}, {2'd0}};

assign trunc_ln818_10_fu_636_p4 = {{r_V_12_fu_630_p2[10:3]}};

assign trunc_ln818_12_fu_669_p4 = {{r_V_14_fu_663_p2[10:3]}};

assign trunc_ln818_13_fu_316_p1 = p_read4_int_reg;

assign trunc_ln818_13_fu_316_p4 = {{trunc_ln818_13_fu_316_p1[7:3]}};

assign trunc_ln818_14_fu_356_p4 = {{r_V_15_fu_350_p2[10:3]}};

assign trunc_ln818_15_fu_366_p1 = p_read4_int_reg;

assign trunc_ln818_15_fu_366_p4 = {{trunc_ln818_15_fu_366_p1[7:1]}};

assign trunc_ln818_16_fu_398_p4 = {{r_V_16_fu_392_p2[10:3]}};

assign trunc_ln818_18_fu_446_p4 = {{r_V_18_fu_440_p2[10:3]}};

assign trunc_ln818_1_fu_543_p4 = {{r_V_6_fu_537_p2[10:3]}};

assign trunc_ln818_20_fu_472_p1 = p_read5_int_reg;

assign trunc_ln818_20_fu_472_p4 = {{trunc_ln818_20_fu_472_p1[7:1]}};

assign trunc_ln818_4_fu_599_p4 = {{r_V_8_fu_593_p2[10:3]}};

assign trunc_ln818_7_fu_260_p4 = {{r_V_11_fu_238_p2[10:3]}};

assign trunc_ln818_8_fu_116_p1 = p_read_int_reg;

assign trunc_ln818_8_fu_116_p4 = {{trunc_ln818_8_fu_116_p1[7:2]}};

assign trunc_ln818_9_fu_164_p4 = {{r_V_5_fu_158_p2[10:3]}};

assign trunc_ln_fu_298_p1 = p_read3_int_reg;

assign trunc_ln_fu_298_p4 = {{trunc_ln_fu_298_p1[7:1]}};

endmodule //myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s
