// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] p_read;
input  [7:0] p_read1;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
input   ap_ce;

reg[7:0] ap_return_0;
reg[7:0] ap_return_1;
reg[7:0] ap_return_2;
reg[7:0] ap_return_3;

reg   [7:0] p_read13_reg_269;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg  signed [7:0] p_read_13_reg_275;
reg   [5:0] trunc_ln818_34_reg_283;
reg   [6:0] trunc_ln818_37_reg_288;
reg   [4:0] trunc_ln818_38_reg_293;
wire  signed [7:0] sext_ln1273_fu_66_p0;
wire    ap_block_pp0_stage0;
wire  signed [8:0] sext_ln1273_fu_66_p1;
wire   [8:0] r_V_26_fu_70_p2;
wire   [8:0] shl_ln1273_s_fu_116_p3;
wire   [10:0] shl_ln_fu_109_p3;
wire  signed [10:0] sext_ln1273_25_fu_123_p1;
wire   [10:0] r_V_fu_127_p2;
wire   [9:0] shl_ln1273_8_fu_143_p3;
wire  signed [10:0] sext_ln1273_26_fu_150_p1;
wire  signed [10:0] sext_ln1273_24_fu_106_p1;
wire   [10:0] r_V_25_fu_154_p2;
wire   [10:0] r_V_27_fu_173_p2;
wire   [9:0] shl_ln1273_9_fu_189_p3;
wire  signed [10:0] sext_ln1273_27_fu_196_p1;
wire   [10:0] r_V_28_fu_200_p2;
wire   [7:0] trunc_ln818_36_fu_206_p4;
wire   [7:0] trunc_ln_fu_133_p4;
wire   [7:0] trunc_ln818_s_fu_160_p4;
wire  signed [7:0] sext_ln818_6_fu_170_p1;
wire  signed [7:0] sext_ln818_fu_216_p1;
wire   [7:0] trunc_ln818_35_fu_179_p4;
wire  signed [7:0] sext_ln818_7_fu_219_p1;
wire   [7:0] add_ln813_fu_222_p2;
wire   [7:0] add_ln813_34_fu_228_p2;
wire   [7:0] add_ln813_35_fu_233_p2;
wire   [7:0] add_ln813_36_fu_239_p2;
reg    ap_ce_reg;
reg   [7:0] ap_return_0_int_reg;
reg   [7:0] ap_return_1_int_reg;
reg   [7:0] ap_return_2_int_reg;
reg   [7:0] ap_return_3_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln813_fu_222_p2;
        ap_return_1_int_reg <= add_ln813_34_fu_228_p2;
        ap_return_2_int_reg <= add_ln813_35_fu_233_p2;
        ap_return_3_int_reg <= add_ln813_36_fu_239_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        p_read13_reg_269 <= p_read1;
        p_read_13_reg_275 <= p_read;
        trunc_ln818_34_reg_283 <= {{r_V_26_fu_70_p2[8:3]}};
        trunc_ln818_37_reg_288 <= {{p_read1[7:1]}};
        trunc_ln818_38_reg_293 <= {{p_read1[7:3]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln813_fu_222_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln813_34_fu_228_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln813_35_fu_233_p2;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln813_36_fu_239_p2;
    end else begin
        ap_return_3 = 'bx;
    end
end

assign add_ln813_34_fu_228_p2 = (trunc_ln818_s_fu_160_p4 + p_read13_reg_269);

assign add_ln813_35_fu_233_p2 = ($signed(sext_ln818_6_fu_170_p1) + $signed(sext_ln818_fu_216_p1));

assign add_ln813_36_fu_239_p2 = ($signed(trunc_ln818_35_fu_179_p4) + $signed(sext_ln818_7_fu_219_p1));

assign add_ln813_fu_222_p2 = (trunc_ln818_36_fu_206_p4 + trunc_ln_fu_133_p4);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign r_V_25_fu_154_p2 = ($signed(sext_ln1273_26_fu_150_p1) - $signed(sext_ln1273_24_fu_106_p1));

assign r_V_26_fu_70_p2 = ($signed(9'd0) - $signed(sext_ln1273_fu_66_p1));

assign r_V_27_fu_173_p2 = ($signed(11'd0) - $signed(sext_ln1273_26_fu_150_p1));

assign r_V_28_fu_200_p2 = ($signed(11'd0) - $signed(sext_ln1273_27_fu_196_p1));

assign r_V_fu_127_p2 = ($signed(shl_ln_fu_109_p3) - $signed(sext_ln1273_25_fu_123_p1));

assign sext_ln1273_24_fu_106_p1 = p_read_13_reg_275;

assign sext_ln1273_25_fu_123_p1 = $signed(shl_ln1273_s_fu_116_p3);

assign sext_ln1273_26_fu_150_p1 = $signed(shl_ln1273_8_fu_143_p3);

assign sext_ln1273_27_fu_196_p1 = $signed(shl_ln1273_9_fu_189_p3);

assign sext_ln1273_fu_66_p0 = p_read;

assign sext_ln1273_fu_66_p1 = sext_ln1273_fu_66_p0;

assign sext_ln818_6_fu_170_p1 = $signed(trunc_ln818_34_reg_283);

assign sext_ln818_7_fu_219_p1 = $signed(trunc_ln818_38_reg_293);

assign sext_ln818_fu_216_p1 = $signed(trunc_ln818_37_reg_288);

assign shl_ln1273_8_fu_143_p3 = {{p_read_13_reg_275}, {2'd0}};

assign shl_ln1273_9_fu_189_p3 = {{p_read13_reg_269}, {2'd0}};

assign shl_ln1273_s_fu_116_p3 = {{p_read_13_reg_275}, {1'd0}};

assign shl_ln_fu_109_p3 = {{p_read_13_reg_275}, {3'd0}};

assign trunc_ln818_35_fu_179_p4 = {{r_V_27_fu_173_p2[10:3]}};

assign trunc_ln818_36_fu_206_p4 = {{r_V_28_fu_200_p2[10:3]}};

assign trunc_ln818_s_fu_160_p4 = {{r_V_25_fu_154_p2[10:3]}};

assign trunc_ln_fu_133_p4 = {{r_V_fu_127_p2[10:3]}};

endmodule //myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config11_s
