// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_relu_config10_s (
        ap_ready,
        p_read,
        p_read1,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;

wire   [0:0] icmp_ln1649_fu_40_p2;
wire   [6:0] trunc_ln40_14_fu_36_p1;
wire   [6:0] datareg_V_fu_46_p3;
wire   [0:0] icmp_ln1649_14_fu_58_p2;
wire   [6:0] trunc_ln40_fu_32_p1;
wire   [6:0] datareg_V_14_fu_64_p3;
wire   [7:0] zext_ln45_fu_54_p1;
wire   [7:0] zext_ln45_14_fu_72_p1;

assign ap_ready = 1'b1;

assign datareg_V_14_fu_64_p3 = ((icmp_ln1649_14_fu_58_p2[0:0] == 1'b1) ? trunc_ln40_fu_32_p1 : 7'd0);

assign datareg_V_fu_46_p3 = ((icmp_ln1649_fu_40_p2[0:0] == 1'b1) ? trunc_ln40_14_fu_36_p1 : 7'd0);

assign trunc_ln40_14_fu_36_p1 = p_read[6:0];

assign trunc_ln40_fu_32_p1 = p_read1[6:0];

assign zext_ln45_14_fu_72_p1 = datareg_V_14_fu_64_p3;

assign zext_ln45_fu_54_p1 = datareg_V_fu_46_p3;

assign ap_return_0 = zext_ln45_fu_54_p1;

assign ap_return_1 = zext_ln45_14_fu_72_p1;

assign icmp_ln1649_14_fu_58_p2 = (($signed(p_read1) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_fu_40_p2 = (($signed(p_read) > $signed(8'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_relu_config10_s
