// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s (
        ap_clk,
        ap_rst,
        p_read1,
        p_read2,
        p_read3,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
input   ap_ce;

reg[7:0] ap_return_0;
reg[7:0] ap_return_1;
reg[7:0] ap_return_2;

wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] trunc_ln818_12_reg_248;
reg   [6:0] trunc_ln818_12_reg_248_pp0_iter1_reg;
reg   [6:0] trunc_ln818_12_reg_248_pp0_iter2_reg;
reg   [7:0] trunc_ln818_13_reg_253;
reg   [7:0] trunc_ln818_13_reg_253_pp0_iter1_reg;
reg   [7:0] trunc_ln818_13_reg_253_pp0_iter2_reg;
reg   [7:0] trunc_ln_reg_258;
reg   [7:0] trunc_ln818_s_reg_263;
wire   [4:0] grp_fu_64_p1;
wire    ap_block_pp0_stage0;
wire   [5:0] grp_fu_67_p1;
wire  signed [7:0] trunc_ln818_12_fu_143_p1;
wire   [5:0] trunc_ln1273_fu_153_p1;
wire   [10:0] shl_ln1273_6_fu_165_p3;
wire   [10:0] shl_ln_fu_157_p3;
wire   [10:0] r_V_fu_173_p2;
wire   [10:0] grp_fu_67_p2;
wire   [10:0] grp_fu_64_p2;
wire  signed [7:0] sext_ln818_fu_209_p1;
wire   [7:0] add_ln813_14_fu_217_p2;
wire   [7:0] add_ln813_fu_212_p2;
reg    grp_fu_64_ce;
reg    grp_fu_67_ce;
reg    ap_ce_reg;
reg  signed [7:0] p_read1_int_reg;
reg  signed [7:0] p_read2_int_reg;
reg   [7:0] p_read3_int_reg;
reg   [7:0] ap_return_0_int_reg;
reg   [7:0] ap_return_1_int_reg;
reg   [7:0] ap_return_2_int_reg;

myproject_mul_8s_5ns_11_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 11 ))
mul_8s_5ns_11_3_0_U87(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_read2_int_reg),
    .din1(grp_fu_64_p1),
    .ce(grp_fu_64_ce),
    .dout(grp_fu_64_p2)
);

myproject_mul_8s_6ns_11_3_0 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_8s_6ns_11_3_0_U88(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_read1_int_reg),
    .din1(grp_fu_67_p1),
    .ce(grp_fu_67_ce),
    .dout(grp_fu_67_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln813_14_fu_217_p2;
        ap_return_1_int_reg <= add_ln813_fu_212_p2;
        ap_return_2_int_reg <= trunc_ln818_s_reg_263;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        trunc_ln818_12_reg_248 <= {{trunc_ln818_12_fu_143_p1[7:1]}};
        trunc_ln818_12_reg_248_pp0_iter1_reg <= trunc_ln818_12_reg_248;
        trunc_ln818_12_reg_248_pp0_iter2_reg <= trunc_ln818_12_reg_248_pp0_iter1_reg;
        trunc_ln818_13_reg_253 <= {{r_V_fu_173_p2[10:3]}};
        trunc_ln818_13_reg_253_pp0_iter1_reg <= trunc_ln818_13_reg_253;
        trunc_ln818_13_reg_253_pp0_iter2_reg <= trunc_ln818_13_reg_253_pp0_iter1_reg;
        trunc_ln818_s_reg_263 <= {{grp_fu_64_p2[10:3]}};
        trunc_ln_reg_258 <= {{grp_fu_67_p2[10:3]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln813_14_fu_217_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln813_fu_212_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = trunc_ln818_s_reg_263;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_64_ce = 1'b1;
    end else begin
        grp_fu_64_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_67_ce = 1'b1;
    end else begin
        grp_fu_67_ce = 1'b0;
    end
end

assign add_ln813_14_fu_217_p2 = (trunc_ln818_s_reg_263 + trunc_ln818_13_reg_253_pp0_iter2_reg);

assign add_ln813_fu_212_p2 = ($signed(trunc_ln_reg_258) + $signed(sext_ln818_fu_209_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign grp_fu_64_p1 = 11'd11;

assign grp_fu_67_p1 = 11'd29;

assign r_V_fu_173_p2 = (shl_ln1273_6_fu_165_p3 - shl_ln_fu_157_p3);

assign sext_ln818_fu_209_p1 = $signed(trunc_ln818_12_reg_248_pp0_iter2_reg);

assign shl_ln1273_6_fu_165_p3 = {{p_read3_int_reg}, {3'd0}};

assign shl_ln_fu_157_p3 = {{trunc_ln1273_fu_153_p1}, {5'd0}};

assign trunc_ln1273_fu_153_p1 = p_read3_int_reg[5:0];

assign trunc_ln818_12_fu_143_p1 = p_read2_int_reg;

endmodule //myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s
