-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

attribute shreg_extract : string;
    signal p_read_8_reg_765 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read_9_reg_771 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_s_reg_778 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_12_reg_783 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_7_fu_532_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_7_reg_788 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_12_fu_544_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_12_reg_793 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_18_fu_578_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_18_reg_798 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_22_fu_606_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_22_reg_803 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_3_fu_102_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal shl_ln1273_4_fu_110_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_4_fu_110_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_4_fu_118_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_3_fu_102_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_4_fu_122_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_9_fu_138_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_9_fu_138_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln1273_5_fu_152_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_5_fu_156_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_5_fu_156_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_6_fu_164_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln1273_fu_168_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_5_fu_152_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_5_fu_174_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_1_fu_190_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_1_fu_190_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_V_6_fu_204_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_6_fu_220_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_7_fu_228_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_7_fu_228_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1273_6_fu_220_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_7_fu_236_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_7_fu_240_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_6_fu_256_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_6_fu_256_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln818_10_fu_270_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_10_fu_270_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln1273_9_fu_284_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1273_10_fu_288_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1273_10_fu_288_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_10_fu_292_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln818_11_fu_298_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_9_fu_312_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_9_fu_312_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_11_fu_320_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_9_fu_284_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_11_fu_324_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_13_fu_340_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_13_fu_340_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln1273_6_fu_354_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_12_fu_360_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_13_fu_376_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_s_fu_380_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_s_fu_380_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_13_fu_376_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_13_fu_388_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_1_fu_404_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_1_fu_404_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_14_fu_412_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_14_fu_416_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_15_fu_432_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_15_fu_448_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_2_fu_452_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_2_fu_452_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_16_fu_460_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_16_fu_464_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_15_fu_448_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_17_fu_480_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_18_fu_496_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_21_fu_512_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_21_fu_512_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_15_fu_394_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_18_fu_470_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_6_fu_526_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_3_fu_308_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_19_fu_486_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_1_fu_200_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_11_fu_538_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_16_fu_422_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_8_fu_128_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_17_fu_438_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_14_fu_550_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_2_fu_210_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1273_12_fu_350_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln818_2_fu_266_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln813_16_fu_562_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln813_fu_568_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_20_fu_502_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_17_fu_572_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_15_fu_556_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_3_fu_246_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_14_fu_366_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln70_4_fu_280_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln70_2_fu_148_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln813_20_fu_590_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln813_1_fu_596_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_4_fu_522_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_21_fu_600_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_19_fu_584_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln70_1_fu_615_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_fu_618_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln_fu_624_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_fu_638_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_fu_645_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln70_fu_612_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_3_fu_649_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_8_fu_668_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_8_fu_675_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln70_3_fu_665_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_8_fu_679_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_9_fu_695_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln818_fu_634_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_4_fu_685_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_fu_711_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_5_fu_717_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_5_fu_701_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_9_fu_727_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_7_fu_655_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_10_fu_732_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_8_fu_722_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_13_fu_738_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_3_int_reg : STD_LOGIC_VECTOR (7 downto 0);


begin




    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln813_12_reg_793 <= add_ln813_12_fu_544_p2;
                add_ln813_18_reg_798 <= add_ln813_18_fu_578_p2;
                add_ln813_22_reg_803 <= add_ln813_22_fu_606_p2;
                add_ln813_7_reg_788 <= add_ln813_7_fu_532_p2;
                p_read_8_reg_765 <= p_read2;
                p_read_9_reg_771 <= p_read;
                trunc_ln818_12_reg_783 <= r_V_11_fu_324_p2(10 downto 3);
                trunc_ln818_s_reg_778 <= r_V_5_fu_174_p2(10 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= add_ln813_8_fu_722_p2;
                ap_return_1_int_reg <= add_ln813_13_fu_738_p2;
                ap_return_2_int_reg <= add_ln813_18_reg_798;
                ap_return_3_int_reg <= add_ln813_22_reg_803;
            end if;
        end if;
    end process;
    add_ln813_10_fu_732_p2 <= std_logic_vector(unsigned(add_ln813_9_fu_727_p2) + unsigned(trunc_ln818_7_fu_655_p4));
    add_ln813_11_fu_538_p2 <= std_logic_vector(unsigned(trunc_ln818_19_fu_486_p4) + unsigned(sext_ln818_1_fu_200_p1));
    add_ln813_12_fu_544_p2 <= std_logic_vector(unsigned(add_ln813_11_fu_538_p2) + unsigned(trunc_ln818_16_fu_422_p4));
    add_ln813_13_fu_738_p2 <= std_logic_vector(unsigned(add_ln813_12_reg_793) + unsigned(add_ln813_10_fu_732_p2));
    add_ln813_14_fu_550_p2 <= std_logic_vector(unsigned(trunc_ln818_8_fu_128_p4) + unsigned(trunc_ln818_17_fu_438_p4));
    add_ln813_15_fu_556_p2 <= std_logic_vector(unsigned(add_ln813_14_fu_550_p2) + unsigned(trunc_ln818_2_fu_210_p4));
    add_ln813_16_fu_562_p2 <= std_logic_vector(signed(sext_ln1273_12_fu_350_p1) + signed(sext_ln818_2_fu_266_p1));
    add_ln813_17_fu_572_p2 <= std_logic_vector(signed(sext_ln813_fu_568_p1) + signed(trunc_ln818_20_fu_502_p4));
    add_ln813_18_fu_578_p2 <= std_logic_vector(unsigned(add_ln813_17_fu_572_p2) + unsigned(add_ln813_15_fu_556_p2));
    add_ln813_19_fu_584_p2 <= std_logic_vector(unsigned(trunc_ln818_3_fu_246_p4) + unsigned(trunc_ln818_14_fu_366_p4));
    add_ln813_20_fu_590_p2 <= std_logic_vector(signed(sext_ln70_4_fu_280_p1) + signed(sext_ln70_2_fu_148_p1));
    add_ln813_21_fu_600_p2 <= std_logic_vector(signed(sext_ln813_1_fu_596_p1) + signed(sext_ln818_4_fu_522_p1));
    add_ln813_22_fu_606_p2 <= std_logic_vector(unsigned(add_ln813_21_fu_600_p2) + unsigned(add_ln813_19_fu_584_p2));
    add_ln813_5_fu_717_p2 <= std_logic_vector(unsigned(add_ln813_fu_711_p2) + unsigned(trunc_ln818_s_reg_778));
    add_ln813_6_fu_526_p2 <= std_logic_vector(unsigned(trunc_ln818_15_fu_394_p4) + unsigned(trunc_ln818_18_fu_470_p4));
    add_ln813_7_fu_532_p2 <= std_logic_vector(unsigned(add_ln813_6_fu_526_p2) + unsigned(sext_ln818_3_fu_308_p1));
    add_ln813_8_fu_722_p2 <= std_logic_vector(unsigned(add_ln813_7_reg_788) + unsigned(add_ln813_5_fu_717_p2));
    add_ln813_9_fu_727_p2 <= std_logic_vector(unsigned(trunc_ln818_5_fu_701_p4) + unsigned(trunc_ln818_12_reg_783));
    add_ln813_fu_711_p2 <= std_logic_vector(signed(sext_ln818_fu_634_p1) + signed(trunc_ln818_4_fu_685_p4));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(add_ln813_8_fu_722_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= add_ln813_8_fu_722_p2;
        else 
            ap_return_0 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(add_ln813_13_fu_738_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= add_ln813_13_fu_738_p2;
        else 
            ap_return_1 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(add_ln813_18_reg_798, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= add_ln813_18_reg_798;
        else 
            ap_return_2 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_3_assign_proc : process(add_ln813_22_reg_803, ap_ce_reg, ap_return_3_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_3 <= ap_return_3_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_3 <= add_ln813_22_reg_803;
        else 
            ap_return_3 <= "XXXXXXXX";
        end if; 
    end process;

    r_V_10_fu_292_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(sext_ln1273_10_fu_288_p1));
    r_V_11_fu_324_p2 <= std_logic_vector(signed(sext_ln1273_11_fu_320_p1) + signed(sext_ln1273_9_fu_284_p1));
    r_V_12_fu_360_p2 <= std_logic_vector(unsigned(sub_ln1273_6_fu_354_p2) - unsigned(sext_ln1273_9_fu_284_p1));
    r_V_13_fu_388_p2 <= std_logic_vector(unsigned(shl_ln1273_s_fu_380_p3) - unsigned(sext_ln1273_13_fu_376_p1));
    r_V_14_fu_416_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_14_fu_412_p1));
    r_V_15_fu_432_p2 <= std_logic_vector(signed(sext_ln1273_14_fu_412_p1) + signed(sext_ln1273_13_fu_376_p1));
    r_V_16_fu_464_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_16_fu_460_p1));
    r_V_17_fu_480_p2 <= std_logic_vector(signed(sext_ln1273_15_fu_448_p1) - signed(sext_ln1273_16_fu_460_p1));
    r_V_18_fu_496_p2 <= std_logic_vector(signed(sext_ln1273_16_fu_460_p1) - signed(sext_ln1273_15_fu_448_p1));
    r_V_3_fu_649_p2 <= std_logic_vector(signed(sext_ln1273_fu_645_p1) + signed(sext_ln70_fu_612_p1));
    r_V_4_fu_122_p2 <= std_logic_vector(signed(sext_ln1273_4_fu_118_p1) - signed(shl_ln1273_3_fu_102_p3));
    r_V_5_fu_174_p2 <= std_logic_vector(unsigned(sub_ln1273_fu_168_p2) - unsigned(sext_ln1273_5_fu_152_p1));
    r_V_6_fu_204_p2 <= std_logic_vector(signed(sext_ln1273_6_fu_164_p1) - signed(sext_ln1273_5_fu_152_p1));
    r_V_7_fu_240_p2 <= std_logic_vector(unsigned(shl_ln1273_6_fu_220_p3) - unsigned(sext_ln1273_7_fu_236_p1));
    r_V_8_fu_679_p2 <= std_logic_vector(signed(sext_ln1273_8_fu_675_p1) + signed(sext_ln70_3_fu_665_p1));
    r_V_9_fu_695_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_8_fu_675_p1));
    r_V_fu_618_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(sext_ln70_1_fu_615_p1));
    sext_ln1273_10_fu_288_p0 <= p_read3;
        sext_ln1273_10_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_10_fu_288_p0),9));

        sext_ln1273_11_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_9_fu_312_p3),11));

        sext_ln1273_12_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_13_fu_340_p4),7));

    sext_ln1273_13_fu_376_p0 <= p_read4;
        sext_ln1273_13_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_13_fu_376_p0),11));

        sext_ln1273_14_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_1_fu_404_p3),11));

    sext_ln1273_15_fu_448_p0 <= p_read5;
        sext_ln1273_15_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_15_fu_448_p0),11));

        sext_ln1273_16_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_2_fu_452_p3),11));

        sext_ln1273_4_fu_118_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_4_fu_110_p3),11));

    sext_ln1273_5_fu_152_p0 <= p_read1;
        sext_ln1273_5_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_5_fu_152_p0),11));

        sext_ln1273_6_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_5_fu_156_p3),11));

        sext_ln1273_7_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_7_fu_228_p3),11));

        sext_ln1273_8_fu_675_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_8_fu_668_p3),11));

    sext_ln1273_9_fu_284_p0 <= p_read3;
        sext_ln1273_9_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_9_fu_284_p0),11));

        sext_ln1273_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_638_p3),11));

        sext_ln70_1_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_9_reg_771),9));

        sext_ln70_2_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_9_fu_138_p4),7));

        sext_ln70_3_fu_665_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_8_reg_765),11));

        sext_ln70_4_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_10_fu_270_p4),7));

        sext_ln70_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_9_reg_771),11));

        sext_ln813_1_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_20_fu_590_p2),8));

        sext_ln813_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_16_fu_562_p2),8));

        sext_ln818_1_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_1_fu_190_p4),8));

        sext_ln818_2_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_6_fu_256_p4),7));

        sext_ln818_3_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_11_fu_298_p4),8));

        sext_ln818_4_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_21_fu_512_p4),8));

        sext_ln818_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_624_p4),8));

    shl_ln1273_1_fu_404_p1 <= p_read4;
    shl_ln1273_1_fu_404_p3 <= (shl_ln1273_1_fu_404_p1 & ap_const_lv2_0);
    shl_ln1273_2_fu_452_p1 <= p_read5;
    shl_ln1273_2_fu_452_p3 <= (shl_ln1273_2_fu_452_p1 & ap_const_lv2_0);
    shl_ln1273_3_fu_102_p1 <= p_read;
    shl_ln1273_3_fu_102_p3 <= (shl_ln1273_3_fu_102_p1 & ap_const_lv3_0);
    shl_ln1273_4_fu_110_p1 <= p_read;
    shl_ln1273_4_fu_110_p3 <= (shl_ln1273_4_fu_110_p1 & ap_const_lv1_0);
    shl_ln1273_5_fu_156_p1 <= p_read1;
    shl_ln1273_5_fu_156_p3 <= (shl_ln1273_5_fu_156_p1 & ap_const_lv2_0);
    shl_ln1273_6_fu_220_p1 <= p_read1;
    shl_ln1273_6_fu_220_p3 <= (shl_ln1273_6_fu_220_p1 & ap_const_lv3_0);
    shl_ln1273_7_fu_228_p1 <= p_read1;
    shl_ln1273_7_fu_228_p3 <= (shl_ln1273_7_fu_228_p1 & ap_const_lv1_0);
    shl_ln1273_8_fu_668_p3 <= (p_read_8_reg_765 & ap_const_lv2_0);
    shl_ln1273_9_fu_312_p1 <= p_read3;
    shl_ln1273_9_fu_312_p3 <= (shl_ln1273_9_fu_312_p1 & ap_const_lv2_0);
    shl_ln1273_s_fu_380_p1 <= p_read4;
    shl_ln1273_s_fu_380_p3 <= (shl_ln1273_s_fu_380_p1 & ap_const_lv3_0);
    shl_ln_fu_638_p3 <= (p_read_9_reg_771 & ap_const_lv2_0);
    sub_ln1273_6_fu_354_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_11_fu_320_p1));
    sub_ln1273_fu_168_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_6_fu_164_p1));
    trunc_ln818_10_fu_270_p1 <= p_read2;
    trunc_ln818_10_fu_270_p4 <= trunc_ln818_10_fu_270_p1(7 downto 2);
    trunc_ln818_11_fu_298_p4 <= r_V_10_fu_292_p2(8 downto 3);
    trunc_ln818_13_fu_340_p1 <= p_read3;
    trunc_ln818_13_fu_340_p4 <= trunc_ln818_13_fu_340_p1(7 downto 2);
    trunc_ln818_14_fu_366_p4 <= r_V_12_fu_360_p2(10 downto 3);
    trunc_ln818_15_fu_394_p4 <= r_V_13_fu_388_p2(10 downto 3);
    trunc_ln818_16_fu_422_p4 <= r_V_14_fu_416_p2(10 downto 3);
    trunc_ln818_17_fu_438_p4 <= r_V_15_fu_432_p2(10 downto 3);
    trunc_ln818_18_fu_470_p4 <= r_V_16_fu_464_p2(10 downto 3);
    trunc_ln818_19_fu_486_p4 <= r_V_17_fu_480_p2(10 downto 3);
    trunc_ln818_1_fu_190_p1 <= p_read1;
    trunc_ln818_1_fu_190_p4 <= trunc_ln818_1_fu_190_p1(7 downto 1);
    trunc_ln818_20_fu_502_p4 <= r_V_18_fu_496_p2(10 downto 3);
    trunc_ln818_21_fu_512_p1 <= p_read5;
    trunc_ln818_21_fu_512_p4 <= trunc_ln818_21_fu_512_p1(7 downto 1);
    trunc_ln818_2_fu_210_p4 <= r_V_6_fu_204_p2(10 downto 3);
    trunc_ln818_3_fu_246_p4 <= r_V_7_fu_240_p2(10 downto 3);
    trunc_ln818_4_fu_685_p4 <= r_V_8_fu_679_p2(10 downto 3);
    trunc_ln818_5_fu_701_p4 <= r_V_9_fu_695_p2(10 downto 3);
    trunc_ln818_6_fu_256_p1 <= p_read2;
    trunc_ln818_6_fu_256_p4 <= trunc_ln818_6_fu_256_p1(7 downto 3);
    trunc_ln818_7_fu_655_p4 <= r_V_3_fu_649_p2(10 downto 3);
    trunc_ln818_8_fu_128_p4 <= r_V_4_fu_122_p2(10 downto 3);
    trunc_ln818_9_fu_138_p1 <= p_read;
    trunc_ln818_9_fu_138_p4 <= trunc_ln818_9_fu_138_p1(7 downto 3);
    trunc_ln_fu_624_p4 <= r_V_fu_618_p2(8 downto 3);
end behav;
