-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv11_B : STD_LOGIC_VECTOR (10 downto 0) := "00000001011";
    constant ap_const_lv11_1D : STD_LOGIC_VECTOR (10 downto 0) := "00000011101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

attribute shreg_extract : string;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln818_12_reg_248 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_12_reg_248_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_12_reg_248_pp0_iter2_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_13_reg_253 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_13_reg_253_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_13_reg_253_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_258 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_s_reg_263 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_64_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_fu_67_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln818_12_fu_143_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1273_fu_153_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_6_fu_165_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_fu_157_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_fu_173_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_67_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_64_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln818_fu_209_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_14_fu_217_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_fu_212_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_64_ce : STD_LOGIC;
    signal grp_fu_67_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal p_read1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read3_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (7 downto 0);

    component myproject_mul_8s_5ns_11_3_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_mul_8s_6ns_11_3_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    mul_8s_5ns_11_3_0_U87 : component myproject_mul_8s_5ns_11_3_0
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read2_int_reg,
        din1 => grp_fu_64_p1,
        ce => grp_fu_64_ce,
        dout => grp_fu_64_p2);

    mul_8s_6ns_11_3_0_U88 : component myproject_mul_8s_6ns_11_3_0
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 8,
        din1_WIDTH => 6,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read1_int_reg,
        din1 => grp_fu_67_p1,
        ce => grp_fu_67_ce,
        dout => grp_fu_67_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= add_ln813_14_fu_217_p2;
                ap_return_1_int_reg <= add_ln813_fu_212_p2;
                ap_return_2_int_reg <= trunc_ln818_s_reg_263;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                p_read1_int_reg <= p_read1;
                p_read2_int_reg <= p_read2;
                p_read3_int_reg <= p_read3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                trunc_ln818_12_reg_248 <= trunc_ln818_12_fu_143_p1(7 downto 1);
                trunc_ln818_12_reg_248_pp0_iter1_reg <= trunc_ln818_12_reg_248;
                trunc_ln818_12_reg_248_pp0_iter2_reg <= trunc_ln818_12_reg_248_pp0_iter1_reg;
                trunc_ln818_13_reg_253 <= r_V_fu_173_p2(10 downto 3);
                trunc_ln818_13_reg_253_pp0_iter1_reg <= trunc_ln818_13_reg_253;
                trunc_ln818_13_reg_253_pp0_iter2_reg <= trunc_ln818_13_reg_253_pp0_iter1_reg;
                trunc_ln818_s_reg_263 <= grp_fu_64_p2(10 downto 3);
                trunc_ln_reg_258 <= grp_fu_67_p2(10 downto 3);
            end if;
        end if;
    end process;
    add_ln813_14_fu_217_p2 <= std_logic_vector(unsigned(trunc_ln818_s_reg_263) + unsigned(trunc_ln818_13_reg_253_pp0_iter2_reg));
    add_ln813_fu_212_p2 <= std_logic_vector(unsigned(trunc_ln_reg_258) + unsigned(sext_ln818_fu_209_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(add_ln813_14_fu_217_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= add_ln813_14_fu_217_p2;
        else 
            ap_return_0 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(add_ln813_fu_212_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= add_ln813_fu_212_p2;
        else 
            ap_return_1 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(trunc_ln818_s_reg_263, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= trunc_ln818_s_reg_263;
        else 
            ap_return_2 <= "XXXXXXXX";
        end if; 
    end process;


    grp_fu_64_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_64_ce <= ap_const_logic_1;
        else 
            grp_fu_64_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_64_p1 <= ap_const_lv11_B(5 - 1 downto 0);

    grp_fu_67_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_67_ce <= ap_const_logic_1;
        else 
            grp_fu_67_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_67_p1 <= ap_const_lv11_1D(6 - 1 downto 0);
    r_V_fu_173_p2 <= std_logic_vector(unsigned(shl_ln1273_6_fu_165_p3) - unsigned(shl_ln_fu_157_p3));
        sext_ln818_fu_209_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_12_reg_248_pp0_iter2_reg),8));

    shl_ln1273_6_fu_165_p3 <= (p_read3_int_reg & ap_const_lv3_0);
    shl_ln_fu_157_p3 <= (trunc_ln1273_fu_153_p1 & ap_const_lv5_0);
    trunc_ln1273_fu_153_p1 <= p_read3_int_reg(6 - 1 downto 0);
    trunc_ln818_12_fu_143_p1 <= p_read2_int_reg;
end behav;
