-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
-- Version: 2022.2.2
-- Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config8_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal p_read_4_reg_301 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read_5_reg_307 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_2_reg_313 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln813_fu_204_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_reg_318 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_3_fu_210_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_3_reg_323 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_3_reg_323_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_1_fu_275_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_1_reg_328 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_2_fu_280_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_2_reg_333 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal shl_ln_fu_84_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_fu_92_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_fu_96_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_1_fu_112_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_1_fu_120_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_1_fu_124_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln818_5_fu_140_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_5_fu_140_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_6_fu_154_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_5_fu_176_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1273_4_fu_168_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_4_fu_184_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_4_fu_188_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln_fu_102_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_1_fu_164_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_7_fu_194_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_fu_150_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_2_fu_222_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln70_fu_219_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_2_fu_229_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_3_fu_248_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_3_fu_255_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_2_fu_245_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_3_fu_259_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_4_fu_265_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_3_fu_235_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_2_fu_216_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_4_fu_286_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal p_read_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read3_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (7 downto 0);


begin




    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln813_1_reg_328 <= add_ln813_1_fu_275_p2;
                add_ln813_2_reg_333 <= add_ln813_2_fu_280_p2;
                add_ln813_3_reg_323 <= add_ln813_3_fu_210_p2;
                add_ln813_3_reg_323_pp0_iter1_reg <= add_ln813_3_reg_323;
                add_ln813_reg_318 <= add_ln813_fu_204_p2;
                p_read_4_reg_301 <= p_read2_int_reg;
                p_read_5_reg_307 <= p_read1_int_reg;
                trunc_ln818_2_reg_313 <= r_V_1_fu_124_p2(9 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= add_ln813_1_reg_328;
                ap_return_1_int_reg <= add_ln813_4_fu_286_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                p_read1_int_reg <= p_read1;
                p_read2_int_reg <= p_read2;
                p_read3_int_reg <= p_read3;
                p_read_int_reg <= p_read;
            end if;
        end if;
    end process;
    add_ln813_1_fu_275_p2 <= std_logic_vector(unsigned(add_ln813_reg_318) + unsigned(trunc_ln818_4_fu_265_p4));
    add_ln813_2_fu_280_p2 <= std_logic_vector(unsigned(trunc_ln818_3_fu_235_p4) + unsigned(sext_ln818_2_fu_216_p1));
    add_ln813_3_fu_210_p2 <= std_logic_vector(unsigned(trunc_ln818_7_fu_194_p4) + unsigned(sext_ln818_fu_150_p1));
    add_ln813_4_fu_286_p2 <= std_logic_vector(unsigned(add_ln813_3_reg_323_pp0_iter1_reg) + unsigned(add_ln813_2_reg_333));
    add_ln813_fu_204_p2 <= std_logic_vector(unsigned(trunc_ln_fu_102_p4) + unsigned(sext_ln818_1_fu_164_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(add_ln813_1_reg_328, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= add_ln813_1_reg_328;
        else 
            ap_return_0 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(add_ln813_4_fu_286_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= add_ln813_4_fu_286_p2;
        else 
            ap_return_1 <= "XXXXXXXX";
        end if; 
    end process;

    r_V_1_fu_124_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(sext_ln1273_1_fu_120_p1));
    r_V_2_fu_229_p2 <= std_logic_vector(unsigned(shl_ln1273_2_fu_222_p3) - unsigned(sext_ln70_fu_219_p1));
    r_V_3_fu_259_p2 <= std_logic_vector(signed(sext_ln1273_3_fu_255_p1) + signed(sext_ln1273_2_fu_245_p1));
    r_V_4_fu_188_p2 <= std_logic_vector(unsigned(shl_ln1273_4_fu_168_p3) - unsigned(sext_ln1273_4_fu_184_p1));
    r_V_fu_96_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_fu_92_p1));
        sext_ln1273_1_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_1_fu_112_p3),10));

        sext_ln1273_2_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_4_reg_301),11));

        sext_ln1273_3_fu_255_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_3_fu_248_p3),11));

        sext_ln1273_4_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_5_fu_176_p3),11));

        sext_ln1273_fu_92_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_84_p3),11));

        sext_ln70_fu_219_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_5_reg_307),11));

        sext_ln818_1_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_6_fu_154_p4),8));

        sext_ln818_2_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_2_reg_313),8));

        sext_ln818_fu_150_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_5_fu_140_p4),8));

    shl_ln1273_1_fu_112_p3 <= (p_read_int_reg & ap_const_lv1_0);
    shl_ln1273_2_fu_222_p3 <= (p_read_5_reg_307 & ap_const_lv3_0);
    shl_ln1273_3_fu_248_p3 <= (p_read_4_reg_301 & ap_const_lv2_0);
    shl_ln1273_4_fu_168_p3 <= (p_read3_int_reg & ap_const_lv3_0);
    shl_ln1273_5_fu_176_p3 <= (p_read3_int_reg & ap_const_lv1_0);
    shl_ln_fu_84_p3 <= (p_read_int_reg & ap_const_lv2_0);
    trunc_ln818_3_fu_235_p4 <= r_V_2_fu_229_p2(10 downto 3);
    trunc_ln818_4_fu_265_p4 <= r_V_3_fu_259_p2(10 downto 3);
    trunc_ln818_5_fu_140_p1 <= p_read2_int_reg;
    trunc_ln818_5_fu_140_p4 <= trunc_ln818_5_fu_140_p1(7 downto 1);
    trunc_ln818_6_fu_154_p4 <= p_read3_int_reg(7 downto 2);
    trunc_ln818_7_fu_194_p4 <= r_V_4_fu_188_p2(10 downto 3);
    trunc_ln_fu_102_p4 <= r_V_fu_96_p2(10 downto 3);
end behav;
