-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config11_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config11_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal sext_ln1273_fu_66_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1273_24_fu_70_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_74_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_s_fu_82_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_s_fu_82_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln_fu_74_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_25_fu_90_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_fu_94_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_8_fu_110_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_8_fu_110_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_26_fu_118_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_24_fu_70_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_25_fu_122_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_fu_66_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal r_V_26_fu_138_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln818_34_fu_144_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_V_27_fu_158_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_9_fu_174_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_27_fu_182_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_28_fu_186_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_37_fu_202_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln818_38_fu_216_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln818_36_fu_192_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_fu_100_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_s_fu_128_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_6_fu_154_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_fu_212_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_35_fu_164_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_7_fu_226_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_fu_230_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_34_fu_236_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_35_fu_242_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_36_fu_248_p2 : STD_LOGIC_VECTOR (7 downto 0);


begin



    add_ln813_34_fu_236_p2 <= std_logic_vector(unsigned(trunc_ln818_s_fu_128_p4) + unsigned(p_read1));
    add_ln813_35_fu_242_p2 <= std_logic_vector(signed(sext_ln818_6_fu_154_p1) + signed(sext_ln818_fu_212_p1));
    add_ln813_36_fu_248_p2 <= std_logic_vector(unsigned(trunc_ln818_35_fu_164_p4) + unsigned(sext_ln818_7_fu_226_p1));
    add_ln813_fu_230_p2 <= std_logic_vector(unsigned(trunc_ln818_36_fu_192_p4) + unsigned(trunc_ln_fu_100_p4));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln813_fu_230_p2;
    ap_return_1 <= add_ln813_34_fu_236_p2;
    ap_return_2 <= add_ln813_35_fu_242_p2;
    ap_return_3 <= add_ln813_36_fu_248_p2;
    r_V_25_fu_122_p2 <= std_logic_vector(signed(sext_ln1273_26_fu_118_p1) - signed(sext_ln1273_24_fu_70_p1));
    r_V_26_fu_138_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(sext_ln1273_fu_66_p1));
    r_V_27_fu_158_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_26_fu_118_p1));
    r_V_28_fu_186_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_27_fu_182_p1));
    r_V_fu_94_p2 <= std_logic_vector(unsigned(shl_ln_fu_74_p3) - unsigned(sext_ln1273_25_fu_90_p1));
    sext_ln1273_24_fu_70_p0 <= p_read;
        sext_ln1273_24_fu_70_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_24_fu_70_p0),11));

        sext_ln1273_25_fu_90_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_s_fu_82_p3),11));

        sext_ln1273_26_fu_118_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_8_fu_110_p3),11));

        sext_ln1273_27_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_9_fu_174_p3),11));

    sext_ln1273_fu_66_p0 <= p_read;
        sext_ln1273_fu_66_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_fu_66_p0),9));

        sext_ln818_6_fu_154_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_34_fu_144_p4),8));

        sext_ln818_7_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_38_fu_216_p4),8));

        sext_ln818_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_37_fu_202_p4),8));

    shl_ln1273_8_fu_110_p1 <= p_read;
    shl_ln1273_8_fu_110_p3 <= (shl_ln1273_8_fu_110_p1 & ap_const_lv2_0);
    shl_ln1273_9_fu_174_p3 <= (p_read1 & ap_const_lv2_0);
    shl_ln1273_s_fu_82_p1 <= p_read;
    shl_ln1273_s_fu_82_p3 <= (shl_ln1273_s_fu_82_p1 & ap_const_lv1_0);
    shl_ln_fu_74_p1 <= p_read;
    shl_ln_fu_74_p3 <= (shl_ln_fu_74_p1 & ap_const_lv3_0);
    trunc_ln818_34_fu_144_p4 <= r_V_26_fu_138_p2(8 downto 3);
    trunc_ln818_35_fu_164_p4 <= r_V_27_fu_158_p2(10 downto 3);
    trunc_ln818_36_fu_192_p4 <= r_V_28_fu_186_p2(10 downto 3);
    trunc_ln818_37_fu_202_p4 <= p_read1(7 downto 1);
    trunc_ln818_38_fu_216_p4 <= p_read1(7 downto 3);
    trunc_ln818_s_fu_128_p4 <= r_V_25_fu_122_p2(10 downto 3);
    trunc_ln_fu_100_p4 <= r_V_fu_94_p2(10 downto 3);
end behav;
