-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv11_7E5 : STD_LOGIC_VECTOR (10 downto 0) := "11111100101";
    constant ap_const_lv11_23 : STD_LOGIC_VECTOR (10 downto 0) := "00000100011";
    constant ap_const_lv11_7E3 : STD_LOGIC_VECTOR (10 downto 0) := "11111100011";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_A : STD_LOGIC_VECTOR (7 downto 0) := "00001010";
    constant ap_const_lv8_C : STD_LOGIC_VECTOR (7 downto 0) := "00001100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";

attribute shreg_extract : string;
    signal p_read_6_reg_577 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read17_reg_582 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1273_fu_289_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1273_reg_588 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln818_7_reg_593 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_4_fu_437_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_4_reg_598 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_8_fu_449_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_8_reg_603 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_12_fu_467_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_12_reg_608 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1270_fu_96_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln1270_2_fu_98_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1273_4_fu_308_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1270_2_fu_98_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1270_1_fu_100_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln1270_fu_96_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1270_1_fu_100_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_4_fu_308_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1270_2_fu_98_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln1273_2_fu_323_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1273_2_fu_323_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_7_fu_327_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_4_fu_335_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln1273_3_fu_351_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_9_fu_363_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1273_8_fu_355_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_5_fu_371_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_5_fu_375_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln1273_4_fu_391_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_1_fu_403_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1273_s_fu_395_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_6_fu_411_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_6_fu_415_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_8_fu_341_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_3_fu_431_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_6_fu_298_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_s_fu_421_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_7_fu_443_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_9_fu_381_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_fu_279_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_11_fu_461_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_10_fu_455_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_5_fu_480_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln_fu_473_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_fu_487_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_fu_491_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_6_fu_507_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_3_fu_514_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_3_fu_518_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_5_fu_524_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln818_fu_534_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_fu_539_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_4_fu_497_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_6_fu_550_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_9_fu_555_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_5_fu_545_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (7 downto 0);

    component GN_inference_mul_8s_6s_11_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component GN_inference_mul_8s_7ns_11_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    mul_8s_6s_11_1_0_U53 : component GN_inference_mul_8s_6s_11_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 6,
        dout_WIDTH => 11)
    port map (
        din0 => p_read,
        din1 => mul_ln1270_fu_96_p1,
        dout => mul_ln1270_fu_96_p2);

    mul_8s_7ns_11_1_0_U54 : component GN_inference_mul_8s_7ns_11_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln1270_2_fu_98_p0,
        din1 => mul_ln1270_2_fu_98_p1,
        dout => mul_ln1270_2_fu_98_p2);

    mul_8s_6s_11_1_0_U55 : component GN_inference_mul_8s_6s_11_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 6,
        dout_WIDTH => 11)
    port map (
        din0 => p_read2,
        din1 => mul_ln1270_1_fu_100_p1,
        dout => mul_ln1270_1_fu_100_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1))) then
                add_ln813_12_reg_608 <= add_ln813_12_fu_467_p2;
                add_ln813_4_reg_598 <= add_ln813_4_fu_437_p2;
                add_ln813_8_reg_603 <= add_ln813_8_fu_449_p2;
                p_read17_reg_582 <= p_read1;
                p_read_6_reg_577 <= p_read4;
                trunc_ln1273_reg_588 <= trunc_ln1273_fu_289_p1;
                trunc_ln818_7_reg_593 <= mul_ln1270_2_fu_98_p2(10 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= add_ln813_9_fu_555_p2;
                ap_return_1_int_reg <= add_ln813_5_fu_545_p2;
                ap_return_2_int_reg <= add_ln813_12_reg_608;
            end if;
        end if;
    end process;
    add_ln813_10_fu_455_p2 <= std_logic_vector(unsigned(trunc_ln_fu_279_p4) + unsigned(trunc_ln818_6_fu_298_p4));
    add_ln813_11_fu_461_p2 <= std_logic_vector(unsigned(trunc_ln818_s_fu_421_p4) + unsigned(ap_const_lv8_A));
    add_ln813_12_fu_467_p2 <= std_logic_vector(unsigned(add_ln813_11_fu_461_p2) + unsigned(add_ln813_10_fu_455_p2));
    add_ln813_3_fu_431_p2 <= std_logic_vector(unsigned(trunc_ln818_8_fu_341_p4) + unsigned(ap_const_lv8_A));
    add_ln813_4_fu_437_p2 <= std_logic_vector(unsigned(add_ln813_3_fu_431_p2) + unsigned(trunc_ln818_6_fu_298_p4));
    add_ln813_5_fu_545_p2 <= std_logic_vector(unsigned(add_ln813_4_reg_598) + unsigned(add_ln813_fu_539_p2));
    add_ln813_6_fu_550_p2 <= std_logic_vector(unsigned(trunc_ln818_4_fu_497_p4) + unsigned(trunc_ln818_7_reg_593));
    add_ln813_7_fu_443_p2 <= std_logic_vector(unsigned(trunc_ln818_s_fu_421_p4) + unsigned(ap_const_lv8_C));
    add_ln813_8_fu_449_p2 <= std_logic_vector(unsigned(add_ln813_7_fu_443_p2) + unsigned(trunc_ln818_9_fu_381_p4));
    add_ln813_9_fu_555_p2 <= std_logic_vector(unsigned(add_ln813_8_reg_603) + unsigned(add_ln813_6_fu_550_p2));
    add_ln813_fu_539_p2 <= std_logic_vector(unsigned(trunc_ln818_5_fu_524_p4) + unsigned(shl_ln818_fu_534_p2));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(add_ln813_9_fu_555_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= add_ln813_9_fu_555_p2;
        else 
            ap_return_0 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(add_ln813_5_fu_545_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= add_ln813_5_fu_545_p2;
        else 
            ap_return_1 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(add_ln813_12_reg_608, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= add_ln813_12_reg_608;
        else 
            ap_return_2 <= "XXXXXXXX";
        end if; 
    end process;

    mul_ln1270_1_fu_100_p1 <= ap_const_lv11_7E3(6 - 1 downto 0);
    mul_ln1270_2_fu_98_p0 <= sext_ln1273_4_fu_308_p1(8 - 1 downto 0);
    mul_ln1270_2_fu_98_p1 <= ap_const_lv11_23(7 - 1 downto 0);
    mul_ln1270_fu_96_p1 <= ap_const_lv11_7E5(6 - 1 downto 0);
    r_V_3_fu_518_p2 <= std_logic_vector(unsigned(shl_ln_fu_473_p3) + unsigned(sext_ln1273_3_fu_514_p1));
    r_V_4_fu_335_p2 <= std_logic_vector(unsigned(shl_ln1273_7_fu_327_p3) + unsigned(sext_ln1273_4_fu_308_p1));
    r_V_5_fu_375_p2 <= std_logic_vector(unsigned(shl_ln1273_8_fu_355_p3) - unsigned(sext_ln1273_5_fu_371_p1));
    r_V_6_fu_415_p2 <= std_logic_vector(unsigned(shl_ln1273_s_fu_395_p3) + unsigned(sext_ln1273_6_fu_411_p1));
    r_V_fu_491_p2 <= std_logic_vector(unsigned(shl_ln_fu_473_p3) + unsigned(sext_ln1273_fu_487_p1));
        sext_ln1273_3_fu_514_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_6_fu_507_p3),11));

    sext_ln1273_4_fu_308_p0 <= p_read3;
        sext_ln1273_4_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_4_fu_308_p0),11));

        sext_ln1273_5_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_9_fu_363_p3),11));

        sext_ln1273_6_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_1_fu_403_p3),11));

        sext_ln1273_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_5_fu_480_p3),11));

    shl_ln1273_1_fu_403_p3 <= (p_read5 & ap_const_lv1_0);
    shl_ln1273_5_fu_480_p3 <= (p_read17_reg_582 & ap_const_lv2_0);
    shl_ln1273_6_fu_507_p3 <= (p_read17_reg_582 & ap_const_lv1_0);
    shl_ln1273_7_fu_327_p3 <= (trunc_ln1273_2_fu_323_p1 & ap_const_lv5_0);
    shl_ln1273_8_fu_355_p3 <= (trunc_ln1273_3_fu_351_p1 & ap_const_lv5_0);
    shl_ln1273_9_fu_363_p3 <= (p_read4 & ap_const_lv1_0);
    shl_ln1273_s_fu_395_p3 <= (trunc_ln1273_4_fu_391_p1 & ap_const_lv5_0);
    shl_ln818_fu_534_p2 <= std_logic_vector(shift_left(unsigned(p_read_6_reg_577),to_integer(unsigned('0' & ap_const_lv8_2(8-1 downto 0)))));
    shl_ln_fu_473_p3 <= (trunc_ln1273_reg_588 & ap_const_lv5_0);
    trunc_ln1273_2_fu_323_p0 <= p_read3;
    trunc_ln1273_2_fu_323_p1 <= trunc_ln1273_2_fu_323_p0(6 - 1 downto 0);
    trunc_ln1273_3_fu_351_p1 <= p_read4(6 - 1 downto 0);
    trunc_ln1273_4_fu_391_p1 <= p_read5(6 - 1 downto 0);
    trunc_ln1273_fu_289_p1 <= p_read1(6 - 1 downto 0);
    trunc_ln818_4_fu_497_p4 <= r_V_fu_491_p2(10 downto 3);
    trunc_ln818_5_fu_524_p4 <= r_V_3_fu_518_p2(10 downto 3);
    trunc_ln818_6_fu_298_p4 <= mul_ln1270_1_fu_100_p2(10 downto 3);
    trunc_ln818_8_fu_341_p4 <= r_V_4_fu_335_p2(10 downto 3);
    trunc_ln818_9_fu_381_p4 <= r_V_5_fu_375_p2(10 downto 3);
    trunc_ln818_s_fu_421_p4 <= r_V_6_fu_415_p2(10 downto 3);
    trunc_ln_fu_279_p4 <= mul_ln1270_fu_96_p2(10 downto 3);
end behav;
