// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
input   ap_ce;

reg[7:0] ap_return_0;
reg[7:0] ap_return_1;
reg[7:0] ap_return_2;
reg[7:0] ap_return_3;

reg  signed [7:0] p_read511_reg_587;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg  signed [7:0] p_read39_reg_593;
reg   [7:0] p_read28_reg_599;
reg  signed [7:0] p_read17_reg_605;
reg  signed [7:0] p_read17_reg_605_pp0_iter1_reg;
reg   [7:0] trunc_ln_reg_613;
reg   [7:0] trunc_ln_reg_613_pp0_iter1_reg;
reg   [7:0] trunc_ln818_8_reg_618;
reg   [7:0] trunc_ln818_9_reg_623;
reg   [7:0] trunc_ln818_9_reg_623_pp0_iter1_reg;
reg   [6:0] trunc_ln818_s_reg_628;
reg   [5:0] trunc_ln818_3_reg_633;
reg   [6:0] trunc_ln818_4_reg_638;
reg   [5:0] trunc_ln818_7_reg_643;
reg   [5:0] trunc_ln818_11_reg_648;
wire   [7:0] add_ln813_8_fu_292_p2;
reg   [7:0] add_ln813_8_reg_653;
wire   [6:0] add_ln813_13_fu_298_p2;
reg   [6:0] add_ln813_13_reg_658;
wire   [6:0] add_ln813_fu_459_p2;
reg   [6:0] add_ln813_reg_663;
wire   [7:0] add_ln813_6_fu_465_p2;
reg   [7:0] add_ln813_6_reg_668;
wire   [7:0] add_ln813_9_fu_471_p2;
reg   [7:0] add_ln813_9_reg_673;
reg   [7:0] add_ln813_9_reg_673_pp0_iter2_reg;
wire   [7:0] add_ln813_11_fu_476_p2;
reg   [7:0] add_ln813_11_reg_678;
wire   [7:0] add_ln813_14_fu_484_p2;
reg   [7:0] add_ln813_14_reg_683;
reg   [7:0] add_ln813_14_reg_683_pp0_iter2_reg;
wire   [7:0] add_ln813_16_fu_490_p2;
reg   [7:0] add_ln813_16_reg_688;
wire   [7:0] add_ln813_17_fu_496_p2;
reg   [7:0] add_ln813_17_reg_693;
wire   [7:0] add_ln813_5_fu_539_p2;
reg   [7:0] add_ln813_5_reg_698;
wire   [7:0] add_ln813_7_fu_544_p2;
reg   [7:0] add_ln813_7_reg_703;
wire   [7:0] add_ln813_12_fu_548_p2;
reg   [7:0] add_ln813_12_reg_708;
wire   [7:0] add_ln813_18_fu_553_p2;
reg   [7:0] add_ln813_18_reg_713;
wire  signed [7:0] sext_ln1273_fu_102_p0;
wire    ap_block_pp0_stage0;
wire  signed [7:0] shl_ln_fu_106_p1;
wire   [9:0] shl_ln_fu_106_p3;
wire  signed [10:0] sext_ln1273_6_fu_114_p1;
wire   [10:0] r_V_fu_118_p2;
wire  signed [10:0] sext_ln1273_fu_102_p1;
wire   [10:0] r_V_7_fu_134_p2;
wire   [10:0] r_V_8_fu_150_p2;
wire  signed [7:0] sext_ln818_2_fu_166_p0;
wire  signed [7:0] trunc_ln818_s_fu_170_p1;
wire  signed [8:0] sext_ln818_2_fu_166_p1;
wire   [8:0] r_V_11_fu_180_p2;
wire   [5:0] trunc_ln818_5_fu_206_p4;
wire  signed [7:0] sext_ln1273_12_fu_220_p0;
wire  signed [8:0] sext_ln1273_12_fu_220_p1;
wire   [8:0] r_V_13_fu_224_p2;
wire  signed [7:0] trunc_ln818_11_fu_240_p1;
wire   [5:0] trunc_ln818_12_fu_250_p4;
wire   [4:0] trunc_ln818_13_fu_264_p4;
wire  signed [7:0] trunc_ln818_14_fu_278_p1;
wire   [6:0] trunc_ln818_14_fu_278_p4;
wire  signed [7:0] sext_ln818_6_fu_288_p1;
wire  signed [7:0] sext_ln818_4_fu_260_p1;
wire  signed [6:0] sext_ln1273_9_fu_216_p1;
wire  signed [6:0] sext_ln70_fu_274_p1;
wire   [9:0] shl_ln1273_6_fu_310_p3;
wire  signed [10:0] sext_ln1273_8_fu_317_p1;
wire  signed [10:0] sext_ln818_3_fu_304_p1;
wire   [10:0] r_V_10_fu_321_p2;
wire   [8:0] shl_ln1273_8_fu_350_p3;
wire   [10:0] shl_ln1273_7_fu_343_p3;
wire  signed [10:0] sext_ln1273_10_fu_357_p1;
wire   [10:0] r_V_12_fu_361_p2;
wire   [9:0] tmp_fu_383_p3;
wire  signed [10:0] sext_ln1273_11_fu_377_p1;
wire  signed [10:0] sext_ln1273_13_fu_390_p1;
wire   [10:0] r_V_14_fu_394_p2;
wire   [9:0] tmp_1_fu_416_p3;
wire  signed [10:0] sext_ln818_7_fu_413_p1;
wire  signed [10:0] sext_ln1273_14_fu_423_p1;
wire   [10:0] r_V_15_fu_427_p2;
wire   [10:0] r_V_16_fu_443_p2;
wire  signed [6:0] sext_ln70_1_fu_337_p1;
wire  signed [6:0] sext_ln70_2_fu_410_p1;
wire  signed [7:0] sext_ln818_5_fu_380_p1;
wire  signed [7:0] sext_ln818_fu_307_p1;
wire  signed [7:0] sext_ln818_1_fu_340_p1;
wire   [7:0] trunc_ln818_10_fu_400_p4;
wire  signed [7:0] sext_ln813_fu_481_p1;
wire   [7:0] trunc_ln818_15_fu_433_p4;
wire   [7:0] trunc_ln818_6_fu_367_p4;
wire   [7:0] trunc_ln818_2_fu_327_p4;
wire   [7:0] trunc_ln818_16_fu_449_p4;
wire   [8:0] shl_ln1273_5_fu_509_p3;
wire   [10:0] shl_ln1273_4_fu_502_p3;
wire  signed [10:0] sext_ln1273_7_fu_516_p1;
wire   [10:0] r_V_9_fu_520_p2;
wire  signed [7:0] sext_ln813_1_fu_536_p1;
wire   [7:0] trunc_ln818_1_fu_526_p4;
wire   [7:0] add_ln813_10_fu_557_p2;
wire   [7:0] add_ln813_15_fu_561_p2;
reg    ap_ce_reg;
reg   [7:0] p_read_int_reg;
reg   [7:0] p_read1_int_reg;
reg   [7:0] p_read2_int_reg;
reg   [7:0] p_read3_int_reg;
reg   [7:0] p_read4_int_reg;
reg   [7:0] p_read5_int_reg;
reg   [7:0] ap_return_0_int_reg;
reg   [7:0] ap_return_1_int_reg;
reg   [7:0] ap_return_2_int_reg;
reg   [7:0] ap_return_3_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln813_11_reg_678 <= add_ln813_11_fu_476_p2;
        add_ln813_12_reg_708 <= add_ln813_12_fu_548_p2;
        add_ln813_13_reg_658 <= add_ln813_13_fu_298_p2;
        add_ln813_14_reg_683 <= add_ln813_14_fu_484_p2;
        add_ln813_14_reg_683_pp0_iter2_reg <= add_ln813_14_reg_683;
        add_ln813_16_reg_688 <= add_ln813_16_fu_490_p2;
        add_ln813_17_reg_693 <= add_ln813_17_fu_496_p2;
        add_ln813_18_reg_713 <= add_ln813_18_fu_553_p2;
        add_ln813_5_reg_698 <= add_ln813_5_fu_539_p2;
        add_ln813_6_reg_668 <= add_ln813_6_fu_465_p2;
        add_ln813_7_reg_703 <= add_ln813_7_fu_544_p2;
        add_ln813_8_reg_653 <= add_ln813_8_fu_292_p2;
        add_ln813_9_reg_673 <= add_ln813_9_fu_471_p2;
        add_ln813_9_reg_673_pp0_iter2_reg <= add_ln813_9_reg_673;
        add_ln813_reg_663 <= add_ln813_fu_459_p2;
        p_read17_reg_605 <= p_read1_int_reg;
        p_read17_reg_605_pp0_iter1_reg <= p_read17_reg_605;
        p_read28_reg_599 <= p_read2_int_reg;
        p_read39_reg_593 <= p_read3_int_reg;
        p_read511_reg_587 <= p_read5_int_reg;
        trunc_ln818_11_reg_648 <= {{trunc_ln818_11_fu_240_p1[7:2]}};
        trunc_ln818_3_reg_633 <= {{r_V_11_fu_180_p2[8:3]}};
        trunc_ln818_4_reg_638 <= {{p_read2_int_reg[7:1]}};
        trunc_ln818_7_reg_643 <= {{r_V_13_fu_224_p2[8:3]}};
        trunc_ln818_8_reg_618 <= {{r_V_7_fu_134_p2[10:3]}};
        trunc_ln818_9_reg_623 <= {{r_V_8_fu_150_p2[10:3]}};
        trunc_ln818_9_reg_623_pp0_iter1_reg <= trunc_ln818_9_reg_623;
        trunc_ln818_s_reg_628 <= {{trunc_ln818_s_fu_170_p1[7:1]}};
        trunc_ln_reg_613 <= {{r_V_fu_118_p2[10:3]}};
        trunc_ln_reg_613_pp0_iter1_reg <= trunc_ln_reg_613;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln813_10_fu_557_p2;
        ap_return_1_int_reg <= add_ln813_15_fu_561_p2;
        ap_return_2_int_reg <= add_ln813_18_reg_713;
        ap_return_3_int_reg <= add_ln813_5_reg_698;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read_int_reg <= p_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln813_10_fu_557_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln813_15_fu_561_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln813_18_reg_713;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln813_5_reg_698;
    end else begin
        ap_return_3 = 'bx;
    end
end

assign add_ln813_10_fu_557_p2 = (add_ln813_9_reg_673_pp0_iter2_reg + add_ln813_7_reg_703);

assign add_ln813_11_fu_476_p2 = (trunc_ln818_8_reg_618 + trunc_ln818_10_fu_400_p4);

assign add_ln813_12_fu_548_p2 = (add_ln813_11_reg_678 + trunc_ln818_1_fu_526_p4);

assign add_ln813_13_fu_298_p2 = ($signed(sext_ln1273_9_fu_216_p1) + $signed(sext_ln70_fu_274_p1));

assign add_ln813_14_fu_484_p2 = ($signed(sext_ln813_fu_481_p1) + $signed(trunc_ln818_15_fu_433_p4));

assign add_ln813_15_fu_561_p2 = (add_ln813_14_reg_683_pp0_iter2_reg + add_ln813_12_reg_708);

assign add_ln813_16_fu_490_p2 = (trunc_ln818_6_fu_367_p4 + trunc_ln818_2_fu_327_p4);

assign add_ln813_17_fu_496_p2 = ($signed(sext_ln818_5_fu_380_p1) + $signed(trunc_ln818_16_fu_449_p4));

assign add_ln813_18_fu_553_p2 = (add_ln813_17_reg_693 + add_ln813_16_reg_688);

assign add_ln813_5_fu_539_p2 = ($signed(sext_ln813_1_fu_536_p1) + $signed(trunc_ln818_9_reg_623_pp0_iter1_reg));

assign add_ln813_6_fu_465_p2 = ($signed(sext_ln818_5_fu_380_p1) + $signed(sext_ln818_fu_307_p1));

assign add_ln813_7_fu_544_p2 = (add_ln813_6_reg_668 + trunc_ln_reg_613_pp0_iter1_reg);

assign add_ln813_8_fu_292_p2 = ($signed(sext_ln818_6_fu_288_p1) + $signed(sext_ln818_4_fu_260_p1));

assign add_ln813_9_fu_471_p2 = ($signed(add_ln813_8_reg_653) + $signed(sext_ln818_1_fu_340_p1));

assign add_ln813_fu_459_p2 = ($signed(sext_ln70_1_fu_337_p1) + $signed(sext_ln70_2_fu_410_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign r_V_10_fu_321_p2 = ($signed(sext_ln1273_8_fu_317_p1) + $signed(sext_ln818_3_fu_304_p1));

assign r_V_11_fu_180_p2 = ($signed(9'd0) - $signed(sext_ln818_2_fu_166_p1));

assign r_V_12_fu_361_p2 = ($signed(shl_ln1273_7_fu_343_p3) - $signed(sext_ln1273_10_fu_357_p1));

assign r_V_13_fu_224_p2 = ($signed(9'd0) - $signed(sext_ln1273_12_fu_220_p1));

assign r_V_14_fu_394_p2 = ($signed(sext_ln1273_11_fu_377_p1) - $signed(sext_ln1273_13_fu_390_p1));

assign r_V_15_fu_427_p2 = ($signed(sext_ln818_7_fu_413_p1) - $signed(sext_ln1273_14_fu_423_p1));

assign r_V_16_fu_443_p2 = ($signed(sext_ln1273_14_fu_423_p1) + $signed(sext_ln818_7_fu_413_p1));

assign r_V_7_fu_134_p2 = ($signed(r_V_fu_118_p2) - $signed(sext_ln1273_fu_102_p1));

assign r_V_8_fu_150_p2 = ($signed(sext_ln1273_6_fu_114_p1) + $signed(sext_ln1273_fu_102_p1));

assign r_V_9_fu_520_p2 = ($signed(shl_ln1273_4_fu_502_p3) - $signed(sext_ln1273_7_fu_516_p1));

assign r_V_fu_118_p2 = ($signed(11'd0) - $signed(sext_ln1273_6_fu_114_p1));

assign sext_ln1273_10_fu_357_p1 = $signed(shl_ln1273_8_fu_350_p3);

assign sext_ln1273_11_fu_377_p1 = p_read39_reg_593;

assign sext_ln1273_12_fu_220_p0 = p_read3_int_reg;

assign sext_ln1273_12_fu_220_p1 = sext_ln1273_12_fu_220_p0;

assign sext_ln1273_13_fu_390_p1 = $signed(tmp_fu_383_p3);

assign sext_ln1273_14_fu_423_p1 = $signed(tmp_1_fu_416_p3);

assign sext_ln1273_6_fu_114_p1 = $signed(shl_ln_fu_106_p3);

assign sext_ln1273_7_fu_516_p1 = $signed(shl_ln1273_5_fu_509_p3);

assign sext_ln1273_8_fu_317_p1 = $signed(shl_ln1273_6_fu_310_p3);

assign sext_ln1273_9_fu_216_p1 = $signed(trunc_ln818_5_fu_206_p4);

assign sext_ln1273_fu_102_p0 = p_read_int_reg;

assign sext_ln1273_fu_102_p1 = sext_ln1273_fu_102_p0;

assign sext_ln70_1_fu_337_p1 = $signed(trunc_ln818_3_reg_633);

assign sext_ln70_2_fu_410_p1 = $signed(trunc_ln818_11_reg_648);

assign sext_ln70_fu_274_p1 = $signed(trunc_ln818_13_fu_264_p4);

assign sext_ln813_1_fu_536_p1 = $signed(add_ln813_reg_663);

assign sext_ln813_fu_481_p1 = $signed(add_ln813_13_reg_658);

assign sext_ln818_1_fu_340_p1 = $signed(trunc_ln818_4_reg_638);

assign sext_ln818_2_fu_166_p0 = p_read1_int_reg;

assign sext_ln818_2_fu_166_p1 = sext_ln818_2_fu_166_p0;

assign sext_ln818_3_fu_304_p1 = p_read17_reg_605;

assign sext_ln818_4_fu_260_p1 = $signed(trunc_ln818_12_fu_250_p4);

assign sext_ln818_5_fu_380_p1 = $signed(trunc_ln818_7_reg_643);

assign sext_ln818_6_fu_288_p1 = $signed(trunc_ln818_14_fu_278_p4);

assign sext_ln818_7_fu_413_p1 = p_read511_reg_587;

assign sext_ln818_fu_307_p1 = $signed(trunc_ln818_s_reg_628);

assign shl_ln1273_4_fu_502_p3 = {{p_read17_reg_605_pp0_iter1_reg}, {3'd0}};

assign shl_ln1273_5_fu_509_p3 = {{p_read17_reg_605_pp0_iter1_reg}, {1'd0}};

assign shl_ln1273_6_fu_310_p3 = {{p_read17_reg_605}, {2'd0}};

assign shl_ln1273_7_fu_343_p3 = {{p_read28_reg_599}, {3'd0}};

assign shl_ln1273_8_fu_350_p3 = {{p_read28_reg_599}, {1'd0}};

assign shl_ln_fu_106_p1 = p_read_int_reg;

assign shl_ln_fu_106_p3 = {{shl_ln_fu_106_p1}, {2'd0}};

assign tmp_1_fu_416_p3 = {{p_read511_reg_587}, {2'd0}};

assign tmp_fu_383_p3 = {{p_read39_reg_593}, {2'd0}};

assign trunc_ln818_10_fu_400_p4 = {{r_V_14_fu_394_p2[10:3]}};

assign trunc_ln818_11_fu_240_p1 = p_read3_int_reg;

assign trunc_ln818_12_fu_250_p4 = {{p_read4_int_reg[7:2]}};

assign trunc_ln818_13_fu_264_p4 = {{p_read4_int_reg[7:3]}};

assign trunc_ln818_14_fu_278_p1 = p_read5_int_reg;

assign trunc_ln818_14_fu_278_p4 = {{trunc_ln818_14_fu_278_p1[7:1]}};

assign trunc_ln818_15_fu_433_p4 = {{r_V_15_fu_427_p2[10:3]}};

assign trunc_ln818_16_fu_449_p4 = {{r_V_16_fu_443_p2[10:3]}};

assign trunc_ln818_1_fu_526_p4 = {{r_V_9_fu_520_p2[10:3]}};

assign trunc_ln818_2_fu_327_p4 = {{r_V_10_fu_321_p2[10:3]}};

assign trunc_ln818_5_fu_206_p4 = {{p_read2_int_reg[7:2]}};

assign trunc_ln818_6_fu_367_p4 = {{r_V_12_fu_361_p2[10:3]}};

assign trunc_ln818_s_fu_170_p1 = p_read1_int_reg;

endmodule //myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s
