// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_softmax_stable_ap_fixed_ap_fixed_8_4_5_3_0_softmax_config19_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        p_read,
        p_read1,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [7:0] p_read;
input  [7:0] p_read1;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
reg    ap_block_pp0_stage0_subdone;
wire   [7:0] exp_table_address0;
reg    exp_table_ce0;
wire   [16:0] exp_table_q0;
wire   [7:0] exp_table_address1;
reg    exp_table_ce1;
wire   [16:0] exp_table_q1;
wire   [7:0] invert_table_address0;
reg    invert_table_ce0;
wire   [17:0] invert_table_q0;
reg  signed [7:0] p_read_1_reg_348;
wire    ap_block_pp0_stage0_11001;
reg  signed [7:0] p_read_2_reg_353;
wire   [7:0] x_max_V_fu_110_p3;
reg   [7:0] x_max_V_reg_358;
wire   [7:0] p_Result_s_fu_231_p3;
reg   [7:0] p_Result_s_reg_363;
wire   [7:0] p_Result_5_fu_239_p3;
reg   [7:0] p_Result_5_reg_368;
reg   [16:0] r_V_reg_383;
reg   [16:0] r_V_reg_383_pp0_iter4_reg;
reg   [16:0] r_V_reg_383_pp0_iter5_reg;
reg   [16:0] r_V_reg_383_pp0_iter6_reg;
reg   [16:0] r_V_1_reg_389;
reg   [16:0] r_V_1_reg_389_pp0_iter4_reg;
reg   [16:0] r_V_1_reg_389_pp0_iter5_reg;
reg   [16:0] r_V_1_reg_389_pp0_iter6_reg;
wire   [7:0] p_Result_7_fu_285_p3;
reg   [7:0] p_Result_7_reg_395;
reg   [17:0] inv_exp_sum_V_reg_405;
wire  signed [23:0] sext_ln1273_fu_297_p1;
wire  signed [23:0] grp_fu_336_p2;
reg  signed [23:0] mul_ln1270_reg_426;
wire  signed [23:0] grp_fu_342_p2;
reg  signed [23:0] mul_ln1270_1_reg_431;
wire   [63:0] zext_ln255_fu_247_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln255_1_fu_251_p1;
wire   [63:0] zext_ln265_fu_293_p1;
wire  signed [7:0] icmp_ln1651_fu_98_p0;
wire  signed [7:0] icmp_ln1651_fu_98_p1;
wire   [0:0] icmp_ln1651_fu_98_p2;
wire   [0:0] xor_ln1651_fu_104_p2;
wire  signed [7:0] x_max_V_fu_110_p1;
wire  signed [7:0] x_max_V_fu_110_p2;
wire  signed [8:0] sext_ln1348_fu_118_p1;
wire  signed [8:0] sext_ln1348_1_fu_121_p1;
wire   [8:0] ret_V_fu_124_p2;
wire   [0:0] p_Result_8_fu_130_p3;
wire   [0:0] p_Result_9_fu_142_p3;
wire   [0:0] xor_ln895_fu_150_p2;
wire   [0:0] overflow_fu_156_p2;
wire  signed [8:0] sext_ln1348_2_fu_176_p1;
wire   [8:0] ret_V_1_fu_179_p2;
wire   [0:0] p_Result_10_fu_185_p3;
wire   [0:0] p_Result_11_fu_197_p3;
wire   [0:0] xor_ln895_1_fu_205_p2;
wire   [0:0] overflow_1_fu_211_p2;
wire   [0:0] xor_ln302_fu_162_p2;
wire   [7:0] select_ln346_fu_168_p3;
wire   [7:0] p_Val2_1_fu_138_p1;
wire   [0:0] xor_ln302_1_fu_217_p2;
wire   [7:0] select_ln346_1_fu_223_p3;
wire   [7:0] p_Val2_3_fu_193_p1;
wire   [17:0] zext_ln813_fu_258_p1;
wire   [17:0] zext_ln302_fu_255_p1;
wire   [17:0] p_Val2_4_fu_261_p2;
wire   [0:0] p_Result_12_fu_267_p3;
wire   [7:0] tmp_fu_275_p4;
wire  signed [17:0] grp_fu_336_p0;
wire   [16:0] grp_fu_336_p1;
wire  signed [17:0] grp_fu_342_p0;
wire   [16:0] grp_fu_342_p1;
reg    grp_fu_336_ce;
reg    grp_fu_342_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to9;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [23:0] grp_fu_336_p10;
wire   [23:0] grp_fu_342_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
end

myproject_softmax_stable_ap_fixed_ap_fixed_8_4_5_3_0_softmax_config19_s_exp_table_ROM_Abkb #(
    .DataWidth( 17 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1),
    .q1(exp_table_q1)
);

myproject_softmax_stable_ap_fixed_ap_fixed_8_4_5_3_0_softmax_config19_s_invert_table_ROcud #(
    .DataWidth( 18 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0),
    .q0(invert_table_q0)
);

myproject_mul_mul_18s_17ns_24_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_mul_18s_17ns_24_3_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_336_p0),
    .din1(grp_fu_336_p1),
    .ce(grp_fu_336_ce),
    .dout(grp_fu_336_p2)
);

myproject_mul_mul_18s_17ns_24_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 24 ))
mul_mul_18s_17ns_24_3_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_342_p0),
    .din1(grp_fu_342_p1),
    .ce(grp_fu_342_ce),
    .dout(grp_fu_342_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        inv_exp_sum_V_reg_405 <= invert_table_q0;
        mul_ln1270_1_reg_431 <= grp_fu_342_p2;
        mul_ln1270_reg_426 <= grp_fu_336_p2;
        p_Result_7_reg_395 <= p_Result_7_fu_285_p3;
        r_V_1_reg_389_pp0_iter4_reg <= r_V_1_reg_389;
        r_V_1_reg_389_pp0_iter5_reg <= r_V_1_reg_389_pp0_iter4_reg;
        r_V_1_reg_389_pp0_iter6_reg <= r_V_1_reg_389_pp0_iter5_reg;
        r_V_reg_383_pp0_iter4_reg <= r_V_reg_383;
        r_V_reg_383_pp0_iter5_reg <= r_V_reg_383_pp0_iter4_reg;
        r_V_reg_383_pp0_iter6_reg <= r_V_reg_383_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Result_5_reg_368 <= p_Result_5_fu_239_p3;
        p_Result_s_reg_363 <= p_Result_s_fu_231_p3;
        p_read_1_reg_348 <= p_read1;
        p_read_2_reg_353 <= p_read;
        x_max_V_reg_358 <= x_max_V_fu_110_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_ce))) begin
        r_V_1_reg_389 <= exp_table_q0;
        r_V_reg_383 <= exp_table_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to9 = 1'b1;
    end else begin
        ap_idle_pp0_0to9 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to9 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_ce))) begin
        exp_table_ce0 = 1'b1;
    end else begin
        exp_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_ce))) begin
        exp_table_ce1 = 1'b1;
    end else begin
        exp_table_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_336_ce = 1'b1;
    end else begin
        grp_fu_336_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_342_ce = 1'b1;
    end else begin
        grp_fu_342_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_ce))) begin
        invert_table_ce0 = 1'b1;
    end else begin
        invert_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = {{mul_ln1270_reg_426[23:16]}};

assign ap_return_1 = {{mul_ln1270_1_reg_431[23:16]}};

assign exp_table_address0 = zext_ln255_1_fu_251_p1;

assign exp_table_address1 = zext_ln255_fu_247_p1;

assign grp_fu_336_p0 = sext_ln1273_fu_297_p1;

assign grp_fu_336_p1 = grp_fu_336_p10;

assign grp_fu_336_p10 = r_V_reg_383_pp0_iter6_reg;

assign grp_fu_342_p0 = sext_ln1273_fu_297_p1;

assign grp_fu_342_p1 = grp_fu_342_p10;

assign grp_fu_342_p10 = r_V_1_reg_389_pp0_iter6_reg;

assign icmp_ln1651_fu_98_p0 = p_read;

assign icmp_ln1651_fu_98_p1 = p_read1;

assign icmp_ln1651_fu_98_p2 = (($signed(icmp_ln1651_fu_98_p0) < $signed(icmp_ln1651_fu_98_p1)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln265_fu_293_p1;

assign overflow_1_fu_211_p2 = (xor_ln895_1_fu_205_p2 & p_Result_11_fu_197_p3);

assign overflow_fu_156_p2 = (xor_ln895_fu_150_p2 & p_Result_9_fu_142_p3);

assign p_Result_10_fu_185_p3 = ret_V_1_fu_179_p2[32'd8];

assign p_Result_11_fu_197_p3 = ret_V_1_fu_179_p2[32'd7];

assign p_Result_12_fu_267_p3 = p_Val2_4_fu_261_p2[32'd17];

assign p_Result_5_fu_239_p3 = ((xor_ln302_1_fu_217_p2[0:0] == 1'b1) ? select_ln346_1_fu_223_p3 : p_Val2_3_fu_193_p1);

assign p_Result_7_fu_285_p3 = ((p_Result_12_fu_267_p3[0:0] == 1'b1) ? 8'd127 : tmp_fu_275_p4);

assign p_Result_8_fu_130_p3 = ret_V_fu_124_p2[32'd8];

assign p_Result_9_fu_142_p3 = ret_V_fu_124_p2[32'd7];

assign p_Result_s_fu_231_p3 = ((xor_ln302_fu_162_p2[0:0] == 1'b1) ? select_ln346_fu_168_p3 : p_Val2_1_fu_138_p1);

assign p_Val2_1_fu_138_p1 = ret_V_fu_124_p2[7:0];

assign p_Val2_3_fu_193_p1 = ret_V_1_fu_179_p2[7:0];

assign p_Val2_4_fu_261_p2 = (zext_ln813_fu_258_p1 + zext_ln302_fu_255_p1);

assign ret_V_1_fu_179_p2 = ($signed(sext_ln1348_2_fu_176_p1) - $signed(sext_ln1348_1_fu_121_p1));

assign ret_V_fu_124_p2 = ($signed(sext_ln1348_fu_118_p1) - $signed(sext_ln1348_1_fu_121_p1));

assign select_ln346_1_fu_223_p3 = ((overflow_1_fu_211_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln346_fu_168_p3 = ((overflow_fu_156_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign sext_ln1273_fu_297_p1 = $signed(inv_exp_sum_V_reg_405);

assign sext_ln1348_1_fu_121_p1 = $signed(x_max_V_reg_358);

assign sext_ln1348_2_fu_176_p1 = p_read_1_reg_348;

assign sext_ln1348_fu_118_p1 = p_read_2_reg_353;

assign tmp_fu_275_p4 = {{p_Val2_4_fu_261_p2[17:10]}};

assign x_max_V_fu_110_p1 = p_read;

assign x_max_V_fu_110_p2 = p_read1;

assign x_max_V_fu_110_p3 = ((xor_ln1651_fu_104_p2[0:0] == 1'b1) ? x_max_V_fu_110_p1 : x_max_V_fu_110_p2);

assign xor_ln1651_fu_104_p2 = (icmp_ln1651_fu_98_p2 ^ 1'd1);

assign xor_ln302_1_fu_217_p2 = (p_Result_11_fu_197_p3 ^ p_Result_10_fu_185_p3);

assign xor_ln302_fu_162_p2 = (p_Result_9_fu_142_p3 ^ p_Result_8_fu_130_p3);

assign xor_ln895_1_fu_205_p2 = (p_Result_10_fu_185_p3 ^ 1'd1);

assign xor_ln895_fu_150_p2 = (p_Result_8_fu_130_p3 ^ 1'd1);

assign zext_ln255_1_fu_251_p1 = p_Result_5_reg_368;

assign zext_ln255_fu_247_p1 = p_Result_s_reg_363;

assign zext_ln265_fu_293_p1 = p_Result_7_reg_395;

assign zext_ln302_fu_255_p1 = r_V_reg_383;

assign zext_ln813_fu_258_p1 = r_V_1_reg_389;

endmodule //myproject_softmax_stable_ap_fixed_ap_fixed_8_4_5_3_0_softmax_config19_s
