-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

attribute shreg_extract : string;
    signal p_read26_reg_396 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln818_27_reg_402 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_28_reg_407 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_33_reg_412 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_27_fu_302_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_27_reg_417 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_27_reg_417_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_29_fu_308_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_29_reg_422 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_30_fu_314_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln813_30_reg_427 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln818_29_fu_344_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_29_reg_432 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_fu_354_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_reg_437 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_31_fu_362_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_31_reg_442 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_32_fu_367_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_32_reg_447 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_5_fu_76_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal trunc_ln818_s_fu_80_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_s_fu_80_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl_fu_94_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_5_fu_76_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl_fu_94_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln1270_fu_102_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_fu_118_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_118_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_fu_126_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_fu_130_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln70_fu_146_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_s_fu_150_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_s_fu_150_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_19_fu_158_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln1273_fu_162_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln70_fu_146_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_20_fu_168_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln_fu_184_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_fu_184_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln818_30_fu_198_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln1273_21_fu_212_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_5_fu_216_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_6_fu_224_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_6_fu_224_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_22_fu_232_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_5_fu_216_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_22_fu_236_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_21_fu_212_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_23_fu_252_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_7_fu_268_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1273_7_fu_268_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_23_fu_276_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln1273_17_fu_280_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_24_fu_286_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_31_fu_242_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln818_fu_90_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_26_fu_108_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_32_fu_258_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_cast_fu_194_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln70_5_fu_208_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_4_fu_327_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_20_fu_334_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_3_fu_320_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_21_fu_338_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln813_fu_359_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_28_fu_371_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_33_fu_375_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal p_read_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read3_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (7 downto 0);


begin




    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln813_27_reg_417 <= add_ln813_27_fu_302_p2;
                add_ln813_27_reg_417_pp0_iter1_reg <= add_ln813_27_reg_417;
                add_ln813_29_reg_422 <= add_ln813_29_fu_308_p2;
                add_ln813_30_reg_427 <= add_ln813_30_fu_314_p2;
                add_ln813_31_reg_442 <= add_ln813_31_fu_362_p2;
                add_ln813_32_reg_447 <= add_ln813_32_fu_367_p2;
                add_ln813_reg_437 <= add_ln813_fu_354_p2;
                p_read26_reg_396 <= p_read2_int_reg;
                trunc_ln818_27_reg_402 <= r_V_fu_130_p2(10 downto 3);
                trunc_ln818_28_reg_407 <= r_V_20_fu_168_p2(10 downto 3);
                trunc_ln818_29_reg_432 <= r_V_21_fu_338_p2(10 downto 3);
                trunc_ln818_33_reg_412 <= r_V_24_fu_286_p2(10 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= add_ln813_28_fu_371_p2;
                ap_return_1_int_reg <= add_ln813_31_reg_442;
                ap_return_2_int_reg <= add_ln813_33_fu_375_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                p_read1_int_reg <= p_read1;
                p_read2_int_reg <= p_read2;
                p_read3_int_reg <= p_read3;
                p_read_int_reg <= p_read;
            end if;
        end if;
    end process;
    add_ln813_27_fu_302_p2 <= std_logic_vector(unsigned(trunc_ln818_31_fu_242_p4) + unsigned(sext_ln818_fu_90_p1));
    add_ln813_28_fu_371_p2 <= std_logic_vector(unsigned(add_ln813_27_reg_417_pp0_iter1_reg) + unsigned(add_ln813_reg_437));
    add_ln813_29_fu_308_p2 <= std_logic_vector(unsigned(trunc_ln818_26_fu_108_p4) + unsigned(trunc_ln818_32_fu_258_p4));
    add_ln813_30_fu_314_p2 <= std_logic_vector(signed(trunc_ln818_cast_fu_194_p1) + signed(sext_ln70_5_fu_208_p1));
    add_ln813_31_fu_362_p2 <= std_logic_vector(signed(sext_ln813_fu_359_p1) + signed(add_ln813_29_reg_422));
    add_ln813_32_fu_367_p2 <= std_logic_vector(unsigned(trunc_ln818_27_reg_402) + unsigned(trunc_ln818_33_reg_412));
    add_ln813_33_fu_375_p2 <= std_logic_vector(unsigned(add_ln813_32_reg_447) + unsigned(trunc_ln818_29_reg_432));
    add_ln813_fu_354_p2 <= std_logic_vector(unsigned(trunc_ln818_28_reg_407) + unsigned(trunc_ln818_29_fu_344_p4));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(add_ln813_28_fu_371_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= add_ln813_28_fu_371_p2;
        else 
            ap_return_0 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(add_ln813_31_reg_442, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= add_ln813_31_reg_442;
        else 
            ap_return_1 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(add_ln813_33_fu_375_p2, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= add_ln813_33_fu_375_p2;
        else 
            ap_return_2 <= "XXXXXXXX";
        end if; 
    end process;

    p_shl_fu_94_p1 <= p_read_int_reg;
    p_shl_fu_94_p3 <= (p_shl_fu_94_p1 & ap_const_lv3_0);
    r_V_20_fu_168_p2 <= std_logic_vector(unsigned(sub_ln1273_fu_162_p2) - unsigned(sext_ln70_fu_146_p1));
    r_V_21_fu_338_p2 <= std_logic_vector(signed(sext_ln1273_20_fu_334_p1) - signed(shl_ln1273_3_fu_320_p3));
    r_V_22_fu_236_p2 <= std_logic_vector(signed(sext_ln1273_22_fu_232_p1) - signed(shl_ln1273_5_fu_216_p3));
    r_V_23_fu_252_p2 <= std_logic_vector(unsigned(shl_ln1273_5_fu_216_p3) - unsigned(sext_ln1273_21_fu_212_p1));
    r_V_24_fu_286_p2 <= std_logic_vector(unsigned(sub_ln1273_17_fu_280_p2) - unsigned(sext_ln1273_21_fu_212_p1));
    r_V_fu_130_p2 <= std_logic_vector(signed(sext_ln1273_fu_126_p1) + signed(sext_ln818_5_fu_76_p1));
        sext_ln1273_19_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_s_fu_150_p3),11));

        sext_ln1273_20_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_4_fu_327_p3),11));

    sext_ln1273_21_fu_212_p0 <= p_read3_int_reg;
        sext_ln1273_21_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_21_fu_212_p0),11));

        sext_ln1273_22_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_6_fu_224_p3),11));

        sext_ln1273_23_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_7_fu_268_p3),11));

        sext_ln1273_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_118_p3),11));

        sext_ln70_5_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_30_fu_198_p4),6));

    sext_ln70_fu_146_p0 <= p_read1_int_reg;
        sext_ln70_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_fu_146_p0),11));

        sext_ln813_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_30_reg_427),8));

    sext_ln818_5_fu_76_p0 <= p_read_int_reg;
        sext_ln818_5_fu_76_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln818_5_fu_76_p0),11));

        sext_ln818_fu_90_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_s_fu_80_p4),8));

    shl_ln1273_3_fu_320_p3 <= (p_read26_reg_396 & ap_const_lv3_0);
    shl_ln1273_4_fu_327_p3 <= (p_read26_reg_396 & ap_const_lv1_0);
    shl_ln1273_5_fu_216_p1 <= p_read3_int_reg;
    shl_ln1273_5_fu_216_p3 <= (shl_ln1273_5_fu_216_p1 & ap_const_lv3_0);
    shl_ln1273_6_fu_224_p1 <= p_read3_int_reg;
    shl_ln1273_6_fu_224_p3 <= (shl_ln1273_6_fu_224_p1 & ap_const_lv1_0);
    shl_ln1273_7_fu_268_p1 <= p_read3_int_reg;
    shl_ln1273_7_fu_268_p3 <= (shl_ln1273_7_fu_268_p1 & ap_const_lv2_0);
    shl_ln1273_s_fu_150_p1 <= p_read1_int_reg;
    shl_ln1273_s_fu_150_p3 <= (shl_ln1273_s_fu_150_p1 & ap_const_lv2_0);
    shl_ln_fu_118_p1 <= p_read_int_reg;
    shl_ln_fu_118_p3 <= (shl_ln_fu_118_p1 & ap_const_lv2_0);
    sub_ln1270_fu_102_p2 <= std_logic_vector(signed(sext_ln818_5_fu_76_p1) - signed(p_shl_fu_94_p3));
    sub_ln1273_17_fu_280_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_23_fu_276_p1));
    sub_ln1273_fu_162_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(sext_ln1273_19_fu_158_p1));
    trunc_ln818_26_fu_108_p4 <= sub_ln1270_fu_102_p2(10 downto 3);
    trunc_ln818_29_fu_344_p4 <= r_V_21_fu_338_p2(10 downto 3);
    trunc_ln818_30_fu_198_p4 <= p_read2_int_reg(7 downto 3);
    trunc_ln818_31_fu_242_p4 <= r_V_22_fu_236_p2(10 downto 3);
    trunc_ln818_32_fu_258_p4 <= r_V_23_fu_252_p2(10 downto 3);
        trunc_ln818_cast_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_184_p4),6));

    trunc_ln818_s_fu_80_p1 <= p_read_int_reg;
    trunc_ln818_s_fu_80_p4 <= trunc_ln818_s_fu_80_p1(7 downto 1);
    trunc_ln_fu_184_p1 <= p_read1_int_reg;
    trunc_ln_fu_184_p4 <= trunc_ln_fu_184_p1(7 downto 3);
end behav;
