-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_relu_config4_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_relu_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln1649_fu_88_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_8_fu_84_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal datareg_V_fu_94_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1649_4_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_7_fu_80_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal datareg_V_4_fu_112_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1649_5_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_6_fu_76_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal datareg_V_5_fu_130_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1649_6_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_5_fu_72_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal datareg_V_6_fu_148_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1649_7_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_4_fu_68_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal datareg_V_7_fu_166_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1649_8_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_fu_64_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal datareg_V_8_fu_184_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln45_fu_102_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_4_fu_120_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_5_fu_138_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_6_fu_156_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_7_fu_174_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_8_fu_192_p1 : STD_LOGIC_VECTOR (7 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln45_fu_102_p1;
    ap_return_1 <= zext_ln45_4_fu_120_p1;
    ap_return_2 <= zext_ln45_5_fu_138_p1;
    ap_return_3 <= zext_ln45_6_fu_156_p1;
    ap_return_4 <= zext_ln45_7_fu_174_p1;
    ap_return_5 <= zext_ln45_8_fu_192_p1;
    datareg_V_4_fu_112_p3 <= 
        trunc_ln40_7_fu_80_p1 when (icmp_ln1649_4_fu_106_p2(0) = '1') else 
        ap_const_lv7_0;
    datareg_V_5_fu_130_p3 <= 
        trunc_ln40_6_fu_76_p1 when (icmp_ln1649_5_fu_124_p2(0) = '1') else 
        ap_const_lv7_0;
    datareg_V_6_fu_148_p3 <= 
        trunc_ln40_5_fu_72_p1 when (icmp_ln1649_6_fu_142_p2(0) = '1') else 
        ap_const_lv7_0;
    datareg_V_7_fu_166_p3 <= 
        trunc_ln40_4_fu_68_p1 when (icmp_ln1649_7_fu_160_p2(0) = '1') else 
        ap_const_lv7_0;
    datareg_V_8_fu_184_p3 <= 
        trunc_ln40_fu_64_p1 when (icmp_ln1649_8_fu_178_p2(0) = '1') else 
        ap_const_lv7_0;
    datareg_V_fu_94_p3 <= 
        trunc_ln40_8_fu_84_p1 when (icmp_ln1649_fu_88_p2(0) = '1') else 
        ap_const_lv7_0;
    icmp_ln1649_4_fu_106_p2 <= "1" when (signed(p_read1) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_5_fu_124_p2 <= "1" when (signed(p_read2) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_6_fu_142_p2 <= "1" when (signed(p_read3) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_7_fu_160_p2 <= "1" when (signed(p_read4) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_8_fu_178_p2 <= "1" when (signed(p_read5) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_fu_88_p2 <= "1" when (signed(p_read) > signed(ap_const_lv8_0)) else "0";
    trunc_ln40_4_fu_68_p1 <= p_read4(7 - 1 downto 0);
    trunc_ln40_5_fu_72_p1 <= p_read3(7 - 1 downto 0);
    trunc_ln40_6_fu_76_p1 <= p_read2(7 - 1 downto 0);
    trunc_ln40_7_fu_80_p1 <= p_read1(7 - 1 downto 0);
    trunc_ln40_8_fu_84_p1 <= p_read(7 - 1 downto 0);
    trunc_ln40_fu_64_p1 <= p_read5(7 - 1 downto 0);
    zext_ln45_4_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_4_fu_112_p3),8));
    zext_ln45_5_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_5_fu_130_p3),8));
    zext_ln45_6_fu_156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_6_fu_148_p3),8));
    zext_ln45_7_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_7_fu_166_p3),8));
    zext_ln45_8_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_8_fu_184_p3),8));
    zext_ln45_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_fu_94_p3),8));
end behav;
