-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of myproject_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv11_7E5 : STD_LOGIC_VECTOR (10 downto 0) := "11111100101";
    constant ap_const_lv11_23 : STD_LOGIC_VECTOR (10 downto 0) := "00000100011";
    constant ap_const_lv11_7E3 : STD_LOGIC_VECTOR (10 downto 0) := "11111100011";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_A : STD_LOGIC_VECTOR (7 downto 0) := "00001010";
    constant ap_const_lv8_C : STD_LOGIC_VECTOR (7 downto 0) := "00001100";

attribute shreg_extract : string;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln818_5_reg_573 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_5_reg_573_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_5_reg_573_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1273_4_fu_352_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_9_reg_588 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_9_reg_588_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_s_reg_593 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_s_reg_593_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_s_reg_593_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_1_reg_598 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_1_reg_598_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_1_reg_598_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_fu_471_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_reg_604 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_reg_604_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_reg_604_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_reg_604_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_609 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_7_reg_614 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_8_reg_620 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_3_fu_507_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_3_reg_625 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_7_fu_512_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_7_reg_630 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_4_fu_517_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_4_reg_635 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_6_fu_521_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_6_reg_640 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_8_fu_525_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_8_reg_645 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_10_fu_529_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_10_reg_650 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_11_fu_533_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_11_reg_655 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_96_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_fu_98_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_98_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_100_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1273_fu_279_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_5_fu_291_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln_fu_283_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_fu_299_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_fu_303_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_6_fu_319_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln1273_3_fu_327_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_3_fu_331_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_4_fu_352_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1273_2_fu_357_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1273_2_fu_357_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_7_fu_361_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_4_fu_369_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln1273_3_fu_385_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_9_fu_397_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1273_8_fu_389_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_5_fu_405_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_5_fu_409_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln1273_4_fu_431_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_1_fu_443_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1273_s_fu_435_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_6_fu_451_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_6_fu_455_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_6_fu_337_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln818_fu_425_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_96_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_100_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_98_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln813_9_fu_542_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_5_fu_538_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_12_fu_546_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_96_ce : STD_LOGIC;
    signal grp_fu_98_ce : STD_LOGIC;
    signal grp_fu_100_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal p_read_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read2_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read3_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read4_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read5_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (7 downto 0);

    component myproject_mul_8s_6s_11_3_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_mul_8s_7ns_11_3_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    mul_8s_6s_11_3_0_U53 : component myproject_mul_8s_6s_11_3_0
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 8,
        din1_WIDTH => 6,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read_int_reg,
        din1 => grp_fu_96_p1,
        ce => grp_fu_96_ce,
        dout => grp_fu_96_p2);

    mul_8s_7ns_11_3_0_U54 : component myproject_mul_8s_7ns_11_3_0
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_98_p0,
        din1 => grp_fu_98_p1,
        ce => grp_fu_98_ce,
        dout => grp_fu_98_p2);

    mul_8s_6s_11_3_0_U55 : component myproject_mul_8s_6s_11_3_0
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 8,
        din1_WIDTH => 6,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read2_int_reg,
        din1 => grp_fu_100_p1,
        ce => grp_fu_100_ce,
        dout => grp_fu_100_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln813_10_reg_650 <= add_ln813_10_fu_529_p2;
                add_ln813_11_reg_655 <= add_ln813_11_fu_533_p2;
                add_ln813_3_reg_625 <= add_ln813_3_fu_507_p2;
                add_ln813_4_reg_635 <= add_ln813_4_fu_517_p2;
                add_ln813_6_reg_640 <= add_ln813_6_fu_521_p2;
                add_ln813_7_reg_630 <= add_ln813_7_fu_512_p2;
                add_ln813_8_reg_645 <= add_ln813_8_fu_525_p2;
                add_ln813_reg_604 <= add_ln813_fu_471_p2;
                add_ln813_reg_604_pp0_iter1_reg <= add_ln813_reg_604;
                add_ln813_reg_604_pp0_iter2_reg <= add_ln813_reg_604_pp0_iter1_reg;
                add_ln813_reg_604_pp0_iter3_reg <= add_ln813_reg_604_pp0_iter2_reg;
                trunc_ln818_1_reg_598 <= r_V_6_fu_455_p2(10 downto 3);
                trunc_ln818_1_reg_598_pp0_iter1_reg <= trunc_ln818_1_reg_598;
                trunc_ln818_1_reg_598_pp0_iter2_reg <= trunc_ln818_1_reg_598_pp0_iter1_reg;
                trunc_ln818_5_reg_573 <= r_V_fu_303_p2(10 downto 3);
                trunc_ln818_5_reg_573_pp0_iter1_reg <= trunc_ln818_5_reg_573;
                trunc_ln818_5_reg_573_pp0_iter2_reg <= trunc_ln818_5_reg_573_pp0_iter1_reg;
                trunc_ln818_7_reg_614 <= grp_fu_100_p2(10 downto 3);
                trunc_ln818_8_reg_620 <= grp_fu_98_p2(10 downto 3);
                trunc_ln818_9_reg_588 <= r_V_4_fu_369_p2(10 downto 3);
                trunc_ln818_9_reg_588_pp0_iter1_reg <= trunc_ln818_9_reg_588;
                trunc_ln818_s_reg_593 <= r_V_5_fu_409_p2(10 downto 3);
                trunc_ln818_s_reg_593_pp0_iter1_reg <= trunc_ln818_s_reg_593;
                trunc_ln818_s_reg_593_pp0_iter2_reg <= trunc_ln818_s_reg_593_pp0_iter1_reg;
                trunc_ln_reg_609 <= grp_fu_96_p2(10 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= add_ln813_9_fu_542_p2;
                ap_return_1_int_reg <= add_ln813_5_fu_538_p2;
                ap_return_2_int_reg <= add_ln813_12_fu_546_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                p_read1_int_reg <= p_read1;
                p_read2_int_reg <= p_read2;
                p_read3_int_reg <= p_read3;
                p_read4_int_reg <= p_read4;
                p_read5_int_reg <= p_read5;
                p_read_int_reg <= p_read;
            end if;
        end if;
    end process;
    add_ln813_10_fu_529_p2 <= std_logic_vector(unsigned(trunc_ln_reg_609) + unsigned(trunc_ln818_7_reg_614));
    add_ln813_11_fu_533_p2 <= std_logic_vector(unsigned(trunc_ln818_1_reg_598_pp0_iter2_reg) + unsigned(ap_const_lv8_A));
    add_ln813_12_fu_546_p2 <= std_logic_vector(unsigned(add_ln813_11_reg_655) + unsigned(add_ln813_10_reg_650));
    add_ln813_3_fu_507_p2 <= std_logic_vector(unsigned(trunc_ln818_9_reg_588_pp0_iter1_reg) + unsigned(ap_const_lv8_A));
    add_ln813_4_fu_517_p2 <= std_logic_vector(unsigned(add_ln813_3_reg_625) + unsigned(trunc_ln818_7_reg_614));
    add_ln813_5_fu_538_p2 <= std_logic_vector(unsigned(add_ln813_4_reg_635) + unsigned(add_ln813_reg_604_pp0_iter3_reg));
    add_ln813_6_fu_521_p2 <= std_logic_vector(unsigned(trunc_ln818_5_reg_573_pp0_iter2_reg) + unsigned(trunc_ln818_8_reg_620));
    add_ln813_7_fu_512_p2 <= std_logic_vector(unsigned(trunc_ln818_1_reg_598_pp0_iter1_reg) + unsigned(ap_const_lv8_C));
    add_ln813_8_fu_525_p2 <= std_logic_vector(unsigned(add_ln813_7_reg_630) + unsigned(trunc_ln818_s_reg_593_pp0_iter2_reg));
    add_ln813_9_fu_542_p2 <= std_logic_vector(unsigned(add_ln813_8_reg_645) + unsigned(add_ln813_6_reg_640));
    add_ln813_fu_471_p2 <= std_logic_vector(unsigned(trunc_ln818_6_fu_337_p4) + unsigned(shl_ln818_fu_425_p2));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(add_ln813_9_fu_542_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= add_ln813_9_fu_542_p2;
        else 
            ap_return_0 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(add_ln813_5_fu_538_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= add_ln813_5_fu_538_p2;
        else 
            ap_return_1 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(add_ln813_12_fu_546_p2, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= add_ln813_12_fu_546_p2;
        else 
            ap_return_2 <= "XXXXXXXX";
        end if; 
    end process;


    grp_fu_100_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_100_ce <= ap_const_logic_1;
        else 
            grp_fu_100_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_100_p1 <= ap_const_lv11_7E3(6 - 1 downto 0);

    grp_fu_96_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_96_ce <= ap_const_logic_1;
        else 
            grp_fu_96_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_96_p1 <= ap_const_lv11_7E5(6 - 1 downto 0);

    grp_fu_98_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_98_ce <= ap_const_logic_1;
        else 
            grp_fu_98_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_98_p0 <= sext_ln1273_4_fu_352_p1(8 - 1 downto 0);
    grp_fu_98_p1 <= ap_const_lv11_23(7 - 1 downto 0);
    r_V_3_fu_331_p2 <= std_logic_vector(unsigned(shl_ln_fu_283_p3) + unsigned(sext_ln1273_3_fu_327_p1));
    r_V_4_fu_369_p2 <= std_logic_vector(unsigned(shl_ln1273_7_fu_361_p3) + unsigned(sext_ln1273_4_fu_352_p1));
    r_V_5_fu_409_p2 <= std_logic_vector(unsigned(shl_ln1273_8_fu_389_p3) - unsigned(sext_ln1273_5_fu_405_p1));
    r_V_6_fu_455_p2 <= std_logic_vector(unsigned(shl_ln1273_s_fu_435_p3) + unsigned(sext_ln1273_6_fu_451_p1));
    r_V_fu_303_p2 <= std_logic_vector(unsigned(shl_ln_fu_283_p3) + unsigned(sext_ln1273_fu_299_p1));
        sext_ln1273_3_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_6_fu_319_p3),11));

    sext_ln1273_4_fu_352_p0 <= p_read3_int_reg;
        sext_ln1273_4_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_4_fu_352_p0),11));

        sext_ln1273_5_fu_405_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_9_fu_397_p3),11));

        sext_ln1273_6_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_1_fu_443_p3),11));

        sext_ln1273_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_5_fu_291_p3),11));

    shl_ln1273_1_fu_443_p3 <= (p_read5_int_reg & ap_const_lv1_0);
    shl_ln1273_5_fu_291_p3 <= (p_read1_int_reg & ap_const_lv2_0);
    shl_ln1273_6_fu_319_p3 <= (p_read1_int_reg & ap_const_lv1_0);
    shl_ln1273_7_fu_361_p3 <= (trunc_ln1273_2_fu_357_p1 & ap_const_lv5_0);
    shl_ln1273_8_fu_389_p3 <= (trunc_ln1273_3_fu_385_p1 & ap_const_lv5_0);
    shl_ln1273_9_fu_397_p3 <= (p_read4_int_reg & ap_const_lv1_0);
    shl_ln1273_s_fu_435_p3 <= (trunc_ln1273_4_fu_431_p1 & ap_const_lv5_0);
    shl_ln818_fu_425_p2 <= std_logic_vector(shift_left(unsigned(p_read4_int_reg),to_integer(unsigned('0' & ap_const_lv8_2(8-1 downto 0)))));
    shl_ln_fu_283_p3 <= (trunc_ln1273_fu_279_p1 & ap_const_lv5_0);
    trunc_ln1273_2_fu_357_p0 <= p_read3_int_reg;
    trunc_ln1273_2_fu_357_p1 <= trunc_ln1273_2_fu_357_p0(6 - 1 downto 0);
    trunc_ln1273_3_fu_385_p1 <= p_read4_int_reg(6 - 1 downto 0);
    trunc_ln1273_4_fu_431_p1 <= p_read5_int_reg(6 - 1 downto 0);
    trunc_ln1273_fu_279_p1 <= p_read1_int_reg(6 - 1 downto 0);
    trunc_ln818_6_fu_337_p4 <= r_V_3_fu_331_p2(10 downto 3);
end behav;
