-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_relu_config10_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_relu_config10_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln1649_fu_40_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_14_fu_36_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal datareg_V_fu_46_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln1649_14_fu_58_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln40_fu_32_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal datareg_V_14_fu_64_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln45_fu_54_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln45_14_fu_72_p1 : STD_LOGIC_VECTOR (7 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln45_fu_54_p1;
    ap_return_1 <= zext_ln45_14_fu_72_p1;
    datareg_V_14_fu_64_p3 <= 
        trunc_ln40_fu_32_p1 when (icmp_ln1649_14_fu_58_p2(0) = '1') else 
        ap_const_lv7_0;
    datareg_V_fu_46_p3 <= 
        trunc_ln40_14_fu_36_p1 when (icmp_ln1649_fu_40_p2(0) = '1') else 
        ap_const_lv7_0;
    icmp_ln1649_14_fu_58_p2 <= "1" when (signed(p_read1) > signed(ap_const_lv8_0)) else "0";
    icmp_ln1649_fu_40_p2 <= "1" when (signed(p_read) > signed(ap_const_lv8_0)) else "0";
    trunc_ln40_14_fu_36_p1 <= p_read(7 - 1 downto 0);
    trunc_ln40_fu_32_p1 <= p_read1(7 - 1 downto 0);
    zext_ln45_14_fu_72_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_14_fu_64_p3),8));
    zext_ln45_fu_54_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_V_fu_46_p3),8));
end behav;
