-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal sext_ln1270_fu_36_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl_fu_40_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1270_fu_36_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl_fu_40_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln1270_fu_48_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln_fu_54_p4 : STD_LOGIC_VECTOR (7 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(trunc_ln_fu_54_p4) + unsigned(ap_const_lv8_2));
    p_shl_fu_40_p1 <= p_read;
    p_shl_fu_40_p3 <= (p_shl_fu_40_p1 & ap_const_lv3_0);
    sext_ln1270_fu_36_p0 <= p_read;
        sext_ln1270_fu_36_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1270_fu_36_p0),11));

    sub_ln1270_fu_48_p2 <= std_logic_vector(signed(sext_ln1270_fu_36_p1) - signed(p_shl_fu_40_p3));
    trunc_ln_fu_54_p4 <= sub_ln1270_fu_48_p2(10 downto 3);
end behav;
